# Final Analysis — Automated Pipeline

This notebook fills `finalAnalysis.csv` by:
1. Querying each RAG server (Vector, Graph, Hybrid) for answers
2. Collecting sources/triplets used
3. Computing RAGAS metrics (faithfulness, answer_relevancy, context_precision, context_recall)

**Prerequisites:**
- VectorRAG server running on `localhost:8000`
- GraphRAG server running on `localhost:8001`  
- HybridRAG server running on `localhost:8002`
- Document already uploaded (doc_id: `ceb7c087eb8c`)

**Resume-safe:** Every cell saves to CSV after each question and skips already-filled rows on re-run.
If an API key limit is hit mid-way, just change the key and re-run the same cell — it picks up where it left off.

In [4]:
# ============================================================
# Cell 0: Setup & Configuration
# ============================================================

import pandas as pd
import requests
import json
import time
import os
import sys

# --- Config ---
CSV_PATH = os.path.join(os.path.dirname(os.path.abspath('__file__')), 'finalAnalysis.csv')
VECTOR_API  = 'http://localhost:8000'
GRAPH_API   = 'http://localhost:8001'
HYBRID_API  = 'http://localhost:8002'
DOCUMENT_ID = '4ec93fc12bff'

def is_empty(val):
    """Check if a cell value is empty/NaN/needs filling."""
    if pd.isna(val):
        return True
    s = str(val).strip()
    return s == '' or s == 'nan'

# Load the CSV
df = pd.read_csv(CSV_PATH)
print(f'Loaded {len(df)} questions from finalAnalysis.csv')
print(f'Columns: {list(df.columns)}')
print()
df[['question', 'question_type', 'ground_truth']].head(100)

Loaded 50 questions from finalAnalysis.csv
Columns: ['question', 'question_type', 'ground_truth', 'vectorRAG_answer', 'graphRAG_answer', 'hybridRAG_answer', 'vectorRAG_sources', 'graphRAG_triplets', 'hybridRAG_sources', 'vector_faithfulness', 'graph_faithfulness', 'hybrid_faithfulness', 'vector_answer_relevancy', 'graph_answer_relevancy', 'hybrid_answer_relevancy', 'vector_context_precision', 'graph_context_precision', 'hybrid_context_precision', 'vector_context_recall', 'graph_context_recall', 'hybrid_context_recall', 'combined_faithfulness', 'combined_answer_relevancy', 'combined_context_precision', 'combined_context_recall']

,question,question_type,ground_truth
0,What is the unique identification number (UIN)...,Basic Retrieval,The UIN of the policy is 105N153V04.
1,How does the policy document define 'Age' unde...,Basic Retrieval,'Age' means the age of the Life Assured in com...
2,What is the grace period allowed for a policyh...,Basic Retrieval,A grace period of 15 days from the premium due...
3,Where is the physical communication address of...,Basic Retrieval,"Customer Service Desk, ICICI Prudential Life I..."
4,After how many years from the date of policy i...,Basic Retrieval,No policy of Life Insurance shall be called in...
5,What are the three authorized frequencies for ...,Basic Retrieval,"The premiums can be paid in yearly, half-yearl..."
6,How much does the company charge for issuing a...,Basic Retrieval,The current charge for the issuance of a dupli...
7,Who is defined as an 'Appointee' under Part-B ...,Basic Retrieval,An Appointee is the person appointed by the po...
8,To which parties can benefits be legally payab...,Basic Retrieval,"Benefits are payable to the Policyholder, to t..."
9,What is the maximum compensation limit that th...,Basic Retrieval,The Ombudsman shall not award compensation exc...
10,If a policyholder opts for a monthly premium p...,Numerical Reasoning,A premium loading of 4.5% is applied for the m...
11,What is the Guaranteed Surrender Value (GSV) f...,Numerical Reasoning,The GSV factor for policy year 3 is 35%.
12,For a policy with a Premium Payment Term of 10...,Numerical Reasoning,The GA rate is 15% of the annualized premium f...
13,What was the specific policy loan interest rat...,Numerical Reasoning,The loan interest rate in September 2025 was 8...
14,What is the mathematical formula used to calcu...,Numerical Reasoning,Paid-up GMB = GMB X (number of months for whic...
15,What is the maximum percentage of the Surrende...,Numerical Reasoning,A loan of up to 80% of the Surrender Value can...
16,If the 10-year Government Securities yield is ...,Numerical Reasoning,The interest rate will be 8.00% (since the pol...
17,How is the Death Benefit 'B' calculated under ...,Numerical Reasoning,Death Benefit B is calculated as 105% of the t...
18,Write out the full mathematical formula for ca...,Numerical Reasoning,GSV = (GSV Factor X Total premiums paid) + 30%...
19,Using the formula for policy years 8 to (Polic...,Numerical Reasoning,Using the formula: 50% + 40% x (Policy Year - ...
20,How does converting a policy to 'paid-up' stat...,Multi-Clause Retrieval,"Once a policy becomes paid-up, no future rever..."
21,Compare the foreclosure rules for an active/fu...,Multi-Clause Retrieval,For policies other than in-force and fully pai...
22,What additional documents are required to proc...,Multi-Clause Retrieval,An unnatural death claim requires all standard...
23,Explain the vesting rules when a policy is tak...,Multi-Clause Retrieval,"On reaching 18, the policy vests in the minor ..."
24,What is the general rule regarding a registere...,Multi-Clause Retrieval,"Generally, a transfer or assignment under Sect..."
25,"If a policyholder commits suicide, how does th...",Multi-Clause Retrieval,The payout structure is the same in both scena...
26,How is the policy loan interest rate calculate...,Multi-Clause Retrieval,The loan interest rate is calculated as 150 ba...
27,"Under Section 38, what are the four grounds on...",Multi-Clause Retrieval,An insurer can decline an assignment if they h...
28,How does the grace period differ across premiu...,Multi-Clause Retrieval,The grace period is 15 days for monthly freque...
29,"What are the specific conditions, time limits,...",Multi-Clause Retrieval,The revival application must be made within 5 ...
30,What is the exact waiting period specified in ...,Hallucination Resistance,The document does not contain any details or t...
31,How much additional loyalty bonus is paid dire...,Hallucination Resistance,The document does not mention any 'loyalty bon...
32,Under what circumstances can a policyholder re...,Hallucination Resistance,The document does not outline any terms or opt...
33,Which specific international stock market inde...,Hallucination Resistance,No international stock market index is used. T...
34,What is the maximum age limit up to which a po...,Hallucination Resistance,The document does not state any age limits or ...
35,How does the policy document define the 'Guara...,Hallucination Resistance,The document does not mention or define any 'G...
36,What is the administrative fee and refund poli...,Hallucination Resistance,The document does not provide a refund option ...
37,How many free comprehensive medical examinatio...,Hallucination Resistance,The document does not mention or provide any a...
38,Which specific third-party digital payment app...,Hallucination Resistance,No specific third-party apps like Paytm or Pho...
39,What is the dynamic equity asset allocation ra...,Hallucination Resistance,This policy is a 'Participating Non-Linked Lif...
40,I just got my policy document yesterday but I ...,Realistic User Queries,"Yes, you can request a cancellation within 30 ..."
41,I missed my monthly premium payment date becau...,Realistic User Queries,Your life cover will not stop immediately. Sin...
42,My policy has been in a reduced 'paid-up' stat...,Realistic User Queries,"No, once a policy is converted into a paid-up ..."
43,I am facing a financial emergency and need som...,Realistic User Queries,"Yes, you can borrow against your policy as lon..."
44,"I paid my renewal premium by cheque, but it wa...",Realistic User Queries,"No, you are not safe. The policy terms specify..."
45,My insurance agent offered to collect my renew...,Realistic User Queries,"No, you should not pay him in cash. The policy..."
46,I have lost my original policy bond. Is there ...,Realistic User Queries,"Yes, you can get a duplicate policy document b..."
47,I want to transfer my policy to my brother as ...,Realistic User Queries,You can transfer the policy through an assignm...
48,I want to name my 12-year-old daughter as my p...,Realistic User Queries,"Since your daughter is a minor, you must appoi..."
49,If I am unhappy with how the insurance company...,Realistic User Queries,"If you are unsatisfied, you can escalate the m..."

In [7]:
# ============================================================
# Cell 1: Fill vectorRAG_answer & vectorRAG_sources
# ============================================================
# ► Skips rows that already have vectorRAG_answer filled.
# ► Saves CSV after EACH question so progress is never lost.

df = pd.read_csv(CSV_PATH)

print('=' * 60)
print('  Filling: vectorRAG_answer & vectorRAG_sources')
print('=' * 60)

skipped = 0
filled  = 0

for idx, row in df.iterrows():
    question = row['question']
    
    # --- SKIP if already filled ---
    if not is_empty(row.get('vectorRAG_answer')):
        skipped += 1
        print(f'[{idx+1}/{len(df)}] SKIP (already filled)')
        continue
    
    print(f'\n[{idx+1}/{len(df)}] {question[:80]}...')
    
    try:
        resp = requests.post(
            f'{VECTOR_API}/api/query',
            json={'document_id': DOCUMENT_ID, 'query': question, 'top_k': 5},
            timeout=120
        )
        resp.raise_for_status()
        data = resp.json()
        
        df.at[idx, 'vectorRAG_answer'] = data.get('answer', '')
        sources = data.get('sources', [])
        df.at[idx, 'vectorRAG_sources'] = json.dumps(sources)
        
        print(f'  ✓ Answer: {data["answer"][:100]}...')
        print(f'  ✓ Sources: {len(sources)} chunks retrieved')
        filled += 1
        
    except Exception as e:
        print(f'  ✗ ERROR: {e}')
        print(f'  ⚠ Stopping here. Change API key if needed and re-run this cell.')
        df.to_csv(CSV_PATH, index=False)
        raise  # Stop execution so user can fix the issue
    
    # --- SAVE after each question ---
    df.to_csv(CSV_PATH, index=False)
    time.sleep(1)  # Rate limiting

print(f'\n{"=" * 60}')
print(f'  ✓ Done! Skipped: {skipped}, Newly filled: {filled}')
print(f'  ✓ Saved to CSV')
print('=' * 60)

============================================================
  Filling: vectorRAG_answer & vectorRAG_sources
============================================================

[1/50] What is the unique identification number (UIN) of the ICICI Pru Future Perfect p...

C:\Users\grove\AppData\Local\Temp\ipykernel_32788\1652356306.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'The unique identification number (UIN) of the ICICI Pru Future Perfect policy is 105N153V04.
[Source: Passage 2, Page 1]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, 'vectorRAG_answer'] = data.get('answer', '')
C:\Users\grove\AppData\Local\Temp\ipykernel_32788\1652356306.py:38: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[{"text": "later  of  Policy  Issue  Date  or  Policy  Acceptance  Date. 6.Date  of\nDiscontinuance of the Policy means the due date of the first unpaid\npremium. 7.Date of Maturity means the date specified in the Policy\nSchedule on which the Policy Term ends and the Maturity benefit, if\napplicable, is payable. 8.Death Benefit means the benefit, which is\npayable  on  death  of  the  Life  Assured  during  the  Policy  Term  as\nspecified in the Policy document. 9.Fully paid policy is a policy for\nwhich all premiums have been paid, as per the Premium Payment\nTerm selected, and no further premiums are due.  10.Guaranteed\nMaturity Benefit means the amount specified in the Policy Schedule\nthat is guaranteed to be paid by Us in accordance with the terms of\nthe Policy. 11.Life Assured is the person named in the Policy Schedule\non whose life the Policy has been issued. 12.Maturity Benefit means\nthe benefit , if any, which is payable on the Date of Maturity as", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 1, "chunk_index": 1, "page_chunk_index": 1}, "score": 0.1159}, {"text": "Policy Document - Terms and Conditions of your policy\nICICI Pru Future Perfect\nUIN:105N153V04-A Participating Non-Linked Life Individual Savings\nProduct \nPART-B\nDefinitions\n1.Age means age of the Life Assured in completed years as on the\ndate of commencement of risk of policy .  2.Annualised Premium\nmeans the premium amount payable in a Policy Year excluding the\ntaxes, rider premiums, underwriting extra premiums and loadings for\nmodal premiums. 3.Appointee means the person appointed by You to\nreceive the benefits payable under the Policy till Your Nominee is a\nminor. 4.Claimant  means the person entitled to receive the Policy\nbenefits and includes the policyholder, the nominee, the assignee, the\nlegal heir, the legal representative(s) or the holder(s) of succession\ncertificate as the case may be. 5.Date of commencement of risk is\nlater  of  Policy  Issue  Date  or  Policy  Acceptance  Date. 6.Date  of\nDiscontinuance of the Policy means the due date of the first unpaid", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 1, "chunk_index": 0, "page_chunk_index": 0}, "score": 0.1148}, {"text": "Please refer to Appendix III for details on this section. The Policy is\nsubject  to  the  terms  and  conditions  as  mentioned  in  the  Policy\ndocument and is governed by the Laws of India.\n6.Communication address Our communication address is:  Address:\nCustomer Service Desk\nICICI Prudential Life Insurance Company\nLimited,  Unit  No.  901A,  901B,  1001A  &  1002B,  Prism  Towers,\nMindspace,\n \nLink\n \nRoad,\n \nGoregaon\n \n(West), Mumbai-\n400104. Maharashtra. Telephone:  1800-2660 Facsimile:  022  4205\n8222  E-mail:  lifeline@iciciprulife.com We expect You to immediately\ninform Us about any change in Your address or contact details. \n7.Electronic transactions All transactions carried out by You through\nInternet,  electronic,  call  centres,  tele-service  operations,  computer,\nautomated  machines  network  or  through  other  means  of\ncommunication will be valid and legally binding on Us as well as\nYou. This will be subject to the relevant guidelines and terms and", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 3, "chunk_index": 31, "page_chunk_index": 9}, "score": 0.1109}, {"text": "Insurance  Ombudsman.  We  request  You  to  regularly  check  our\nwebsite  at www.iciciprulife.com or  the  website  of  the  IRDAI\nat www.irdai.gov.in for updated contact details.\n1.  AHMEDABAD: Office  of  the  Insurance  Ombudsman,  Jeevan\nPrakash  Building,  6th  floor,  Tilak  Marg,  Relief  Road,  Ahmedabad\n-380\n \n001\n \nTel:\n \n079\n \n-\n \n25501201/02/05/06\n \nEmail:\nbimalokpal.ahmedabad@cioins.co.in  Areas of Jurisdiction: Gujarat ,\nDadra & Nagar Haveli, Daman and Diu\n2. BENGALURU: Office of Insurance Ombudsman, Jeevan Soudha\nBuilding, PID No. 57-27-N-19, Ground Floor, 19/19, 24th Main Road,\nJP Nagar, 1st Phase, Bengaluru \u2013 560078 Tel: 080 - 26652048 /\n26652049  Email:  bimalokpal.bengaluru@cioins.co.in\n Areas  of\nJurisdiction: Karnataka\n3. BHOPAL: Office of the Insurance Ombudsman, 1 st floor, \u201cJeevan\nShikha\u201d, 60-B, Hoshangabad Road, Opp. Gayatri Mandir, Bhopal \u2013\n462011.  Tel:  0755-2769201,  2769202  and  2769203  Email:\nbimalokpal.bhopal@cioins.co.in\n Areas  of  Jurisdiction:", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 5, "chunk_index": 48, "page_chunk_index": 3}, "score": 0.1104}, {"text": "or  Company  means  ICICI  Prudential  Life  Insurance  Company\nLimited.\nPART-C\n1.Benefits payable:\n1.Death Benefit\ni. On death of the Life Assured during the Policy Term, for a Premium\nPaying or Fully Paid Policy, the following will be payable:  Death\nBenefit = Higher of (A,B), Where, A = Sum Assured on Death, plus\nsubsisting  bonuses*  already  accrued,  plus  accrued  Guaranteed\nAdditions B  =  105%  of  total  premiums  received  till  the  date  of\ndeath Sum  Assured  on  Death  is  defined  as,  highest  of \u2022  10  X\nAnnualised Premium \u2022 Guaranteed Maturity Benefit (GMB) *Bonuses\nconsist of accrued reversionary bonuses, interim bonus and terminal\nbonus,  if  declared. For  policies  issued  on  minor  life,  Date  of\ncommencement  of  risk  is  later  of  Policy  Issue  Date  or  Policy\nAcceptance  Date. ii.  On  payment  of  Death  Benefit  the  policy  will\nterminate and all rights, benefits and interests under the policy will", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 1, "chunk_index": 7, "page_chunk_index": 7}, "score": 0.1097}]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, 'vectorRAG_sources'] = json.dumps(sources)

  ✓ Answer: The unique identification number (UIN) of the ICICI Pru Future Perfect policy is 105N153V04.
[Sourc...
  ✓ Sources: 5 chunks retrieved

[2/50] How does the policy document define 'Age' under Part-B?...
  ✓ Answer: According to Part-B of the policy document, 'Age' is defined as "age of the Life Assured in complete...
  ✓ Sources: 5 chunks retrieved

[3/50] What is the grace period allowed for a policyholder who has chosen a monthly pre...
  ✓ Answer: The grace period allowed for a policyholder who has chosen a monthly premium frequency is 15 days fo...
  ✓ Sources: 5 chunks retrieved

[4/50] Where is the physical communication address of the ICICI Prudential Life Insuran...
  ✓ Answer: The physical communication address of the ICICI Prudential Life Insurance Customer Service Desk is l...
  ✓ Sources: 5 chunks retrieved

[5/50] After how many years from the date of policy issuance, risk commencement, reviva...
  ✓ Answer: A life insurance policy cannot be questioned on any ground whatsoever after expiry of 3 years from t...
  ✓ Sources: 5 chunks retrieved

[6/50] What are the three authorized frequencies for premium payments under this policy...
  ✓ Answer: The three authorized frequencies for premium payments under this policy are:

1. Half-yearly [Page 2...
  ✓ Sources: 5 chunks retrieved

[7/50] How much does the company charge for issuing a duplicate copy of the policy docu...
  ✓ Answer: The company charges ₹ 200 for issuing a duplicate copy of the policy document, as stated in [Passage...
  ✓ Sources: 5 chunks retrieved

[8/50] Who is defined as an 'Appointee' under Part-B of this policy?...
  ✓ Answer: According to Part-B of the policy, an 'Appointee' is defined as "the person appointed by You to rece...
  ✓ Sources: 5 chunks retrieved

[9/50] To which parties can benefits be legally payable according to Part-D Section 9 o...
  ✓ Answer: According to the provided document sections, benefits are payable to the following parties:
1. The ...
  ✓ Sources: 5 chunks retrieved

[10/50] What is the maximum compensation limit that the Insurance Ombudsman can award un...
  ✓ Answer: The maximum compensation limit that the Insurance Ombudsman can award is Rupees Fifty Lakhs (includi...
  ✓ Sources: 5 chunks retrieved

[11/50] If a policyholder opts for a monthly premium payment mode, what loading percenta...
  ✓ Answer: According to the provided context, if a policyholder opts for a monthly premium payment mode, a load...
  ✓ Sources: 5 chunks retrieved

[12/50] What is the Guaranteed Surrender Value (GSV) factor for a policy surrendered dur...
  ✓ Answer: The Guaranteed Surrender Value (GSV) factor for a policy surrendered during its third policy year is...
  ✓ Sources: 5 chunks retrieved

[13/50] For a policy with a Premium Payment Term of 10 years, what is the Guaranteed Add...
  ✓ Answer: For a policy with a Premium Payment Term of 10 years, the Guaranteed Additions (GAs) rate for policy...
  ✓ Sources: 5 chunks retrieved

[14/50] What was the specific policy loan interest rate applicable in September 2025, an...
  ✓ Answer: The specific policy loan interest rate applicable in September 2025 was 8.00% p.a., compounded half-...
  ✓ Sources: 5 chunks retrieved

[15/50] What is the mathematical formula used to calculate the Paid-up Guaranteed Maturi...
  ✓ Answer: The mathematical formula used to calculate the Paid-up Guaranteed Maturity Benefit (Paid-up GMB) is:...
  ✓ Sources: 5 chunks retrieved

[16/50] What is the maximum percentage of the Surrender Value that a policyholder can bo...
  ✓ Answer: The maximum percentage of the Surrender Value that a policyholder can borrow as a loan is up to 80% ...
  ✓ Sources: 5 chunks retrieved

[17/50] If the 10-year Government Securities yield is sourced at 6.50%, what will be the...
  ✓ Answer: The applicable policy loan interest rate can be calculated based on the information provided in the ...
  ✓ Sources: 5 chunks retrieved

[18/50] How is the Death Benefit 'B' calculated under Part-C?...
  ✓ Answer: The Death Benefit 'B' is calculated as "105% of total premiums received till the date of death" unde...
  ✓ Sources: 5 chunks retrieved

[19/50] Write out the full mathematical formula for calculating the Guaranteed Surrender...
  ✓ Answer: The full mathematical formula for calculating the Guaranteed Surrender Value (GSV) is:
GSV = GSV Fa...
  ✓ Sources: 5 chunks retrieved

[20/50] Using the formula for policy years 8 to (Policy Term less 2), calculate the GSV ...
  ✓ Answer: To calculate the GSV factor for policy year 10 when the total policy term is 15 years, we need to re...
  ✓ Sources: 5 chunks retrieved

[21/50] How does converting a policy to 'paid-up' status affect future reversionary bonu...
  ✓ Answer: Converting a policy to 'paid-up' status affects future reversionary bonuses in that no future bonuse...
  ✓ Sources: 5 chunks retrieved

[22/50] Compare the foreclosure rules for an active/fully paid policy with those for a p...
  ✓ Answer: For an active/fully paid policy, if a loan is outstanding, the policy cannot be foreclosed on the gr...
  ✓ Sources: 5 chunks retrieved

[23/50] What additional documents are required to process a death claim for an unnatural...
  ✓ Answer: To process a death claim for an unnatural death, the following additional documents are required com...
  ✓ Sources: 5 chunks retrieved

[24/50] Explain the vesting rules when a policy is taken on a minor's life, including wh...
  ✓ Answer: When a policy is taken on a minor's life, the policy will vest on them when they attain the age of m...
  ✓ Sources: 5 chunks retrieved

[25/50] What is the general rule regarding a registered nomination when a policy is assi...
  ✓ Answer: According to the provided context, the general rule regarding a registered nomination when a policy ...
  ✓ Sources: 5 chunks retrieved

[26/50] If a policyholder commits suicide, how does the payout structure change if it ha...
  ✓ Answer: According to the provided context, if a policyholder commits suicide within 12 months of risk commen...
  ✓ Sources: 5 chunks retrieved

[27/50] How is the policy loan interest rate calculated, how frequently is it reviewed, ...
  ✓ Answer: The policy loan interest rate is calculated as 150 basis points in addition to the prevailing yield ...
  ✓ Sources: 5 chunks retrieved

[28/50] Under Section 38, what are the four grounds on which an insurer can decline to a...
  ✓ Answer: Under Section 38, the four grounds on which an insurer can decline to act on a policy transfer are:
...
  ✓ Sources: 5 chunks retrieved

[29/50] How does the grace period differ across premium frequencies, and what happens to...
  ✓ Answer: The grace period differs across premium frequencies in the following manner: if the policyholder has...
  ✓ Sources: 5 chunks retrieved

[30/50] What are the specific conditions, time limits, and late payment interest rate ca...
  ✓ Answer: To revive a discontinued policy, the policyholder must meet the following conditions and time limits...
  ✓ Sources: 5 chunks retrieved

[31/50] What is the exact waiting period specified in this document before a policyholde...
  ✓ Answer: ⚠️ The requested information was not found in the provided document sections. The document may not c...
  ✓ Sources: 5 chunks retrieved

[32/50] How much additional loyalty bonus is paid directly to the policyholder if they m...
  ✓ Answer: ⚠️ The requested information was not found in the provided document sections. The document may not c...
  ✓ Sources: 5 chunks retrieved

[33/50] Under what circumstances can a policyholder request a partial withdrawal from th...
  ✓ Answer: ⚠️ The requested information was not found in the provided document sections. The document may not c...
  ✓ Sources: 5 chunks retrieved

[34/50] Which specific international stock market index is used to determine the Special...
  ✓ Answer: The Special Surrender Value (SSV) is determined by the Company from time-to-time basis changing econ...
  ✓ Sources: 5 chunks retrieved

[35/50] What is the maximum age limit up to which a policyholder can add an accidental d...
  ✓ Answer: ⚠️ The requested information was not found in the provided document sections. The document may not c...
  ✓ Sources: 5 chunks retrieved

[36/50] How does the policy document define the 'Guaranteed Income Benefit' that is paid...
  ✓ Answer: ⚠️ The requested information was not found in the provided document sections. The document may not c...
  ✓ Sources: 5 chunks retrieved

[37/50] What is the administrative fee and refund policy if a customer decides to cancel...
  ✓ Answer: The administrative fee and refund policy after the 30-day Free Look period has passed is related to ...
  ✓ Sources: 5 chunks retrieved

[38/50] How many free comprehensive medical examinations is the policyholder entitled to...
  ✓ Answer: ⚠️ The requested information was not found in the provided document sections. The document may not c...
  ✓ Sources: 5 chunks retrieved

[39/50] Which specific third-party digital payment apps, such as Paytm or PhonePe, are e...
  ✓ Answer: ⚠️ The requested information was not found in the provided document sections. The document may not c...
  ✓ Sources: 5 chunks retrieved

[40/50] What is the dynamic equity asset allocation ratio used by the fund manager to in...
  ✓ Answer: ⚠️ The requested information was not found in the provided document sections. The document may not c...
  ✓ Sources: 5 chunks retrieved

[41/50] I just got my policy document yesterday but I changed my mind and want to cancel...
  ✓ Answer: You can cancel your policy within 30 days from the date of receipt of the Policy Document, as stated...
  ✓ Sources: 5 chunks retrieved

[42/50] I missed my monthly premium payment date because I was traveling. Will my life c...
  ✓ Answer: According to the provided context, if you miss your monthly premium payment date, you will be given ...
  ✓ Sources: 5 chunks retrieved

[43/50] My policy has been in a reduced 'paid-up' state for the last two years. Will I s...
  ✓ Answer: According to the provided context, a paid-up policy will not be entitled to future reversionary bonu...
  ✓ Sources: 5 chunks retrieved

[44/50] I am facing a financial emergency and need some quick cash. Can I get a loan fro...
  ✓ Answer: You can get a loan from your policy, provided a positive Surrender Value is payable under the Policy...
  ✓ Sources: 5 chunks retrieved

[45/50] I paid my renewal premium by cheque, but it was returned due to insufficient fun...
  ✓ Answer: According to the provided context, if your cheque is returned due to insufficient funds, you are sol...
  ✓ Sources: 5 chunks retrieved

[46/50] My insurance agent offered to collect my renewal premium in cash. Is it okay to ...
  ✓ Answer: According to the provided document, specifically [Passage 1], it is stated that "viii. No person or ...
  ✓ Sources: 5 chunks retrieved

[47/50] I have lost my original policy bond. Is there a way to get a new one, and will i...
  ✓ Answer: You can obtain a duplicate policy document by submitting a written request along with the necessary ...
  ✓ Sources: 5 chunks retrieved

[48/50] I want to transfer my policy to my brother as a gift. What is the process for do...
  ✓ Answer: To transfer your policy to your brother as a gift, the process involves assigning or transferring th...
  ✓ Sources: 5 chunks retrieved

[49/50] I want to name my 12-year-old daughter as my policy beneficiary. What extra step...
  ✓ Answer: To name your 12-year-old daughter as your policy beneficiary, since she is a minor, you need to appo...
  ✓ Sources: 5 chunks retrieved

[50/50] If I am unhappy with how the insurance company's grievance officer resolved my c...
  ✓ Answer: If you are unhappy with how the insurance company's grievance officer resolved your complaint, you c...
  ✓ Sources: 5 chunks retrieved

============================================================
  ✓ Done! Skipped: 0, Newly filled: 50
  ✓ Saved to CSV
============================================================

In [11]:
# ============================================================
# Cell 2: Fill graphRAG_answer & graphRAG_triplets
# ============================================================
# ► Skips rows that already have graphRAG_answer filled.
# ► Saves CSV after EACH question.

df = pd.read_csv(CSV_PATH)

print('=' * 60)
print('  Filling: graphRAG_answer & graphRAG_triplets')
print('=' * 60)

skipped = 0
filled  = 0

for idx, row in df.iterrows():
    question = row['question']
    
    # --- SKIP if already filled ---
    if not is_empty(row.get('graphRAG_answer')):
        skipped += 1
        print(f'[{idx+1}/{len(df)}] SKIP (already filled)')
        continue
    
    print(f'\n[{idx+1}/{len(df)}] {question[:80]}...')
    
    try:
        resp = requests.post(
            f'{GRAPH_API}/api/graph/query',
            json={'document_id': DOCUMENT_ID, 'query': question},
            timeout=120
        )
        resp.raise_for_status()
        data = resp.json()
        
        df.at[idx, 'graphRAG_answer'] = data.get('answer', '')
        triplets = data.get('triplets_used', [])
        df.at[idx, 'graphRAG_triplets'] = json.dumps(triplets)
        
        print(f'  ✓ Answer: {data["answer"][:100]}...')
        print(f'  ✓ Triplets: {len(triplets)} used')
        filled += 1
        
    except Exception as e:
        print(f'  ✗ ERROR: {e}')
        print(f'  ⚠ Stopping here. Change API key if needed and re-run this cell.')
        df.to_csv(CSV_PATH, index=False)
        raise
    
    # --- SAVE after each question ---
    df.to_csv(CSV_PATH, index=False)
    time.sleep(1)

print(f'\n{"=" * 60}')
print(f'  ✓ Done! Skipped: {skipped}, Newly filled: {filled}')
print(f'  ✓ Saved to CSV')
print('=' * 60)

============================================================
  Filling: graphRAG_answer & graphRAG_triplets
============================================================
[1/50] SKIP (already filled)
[2/50] SKIP (already filled)
[3/50] SKIP (already filled)
[4/50] SKIP (already filled)
[5/50] SKIP (already filled)
[6/50] SKIP (already filled)
[7/50] SKIP (already filled)
[8/50] SKIP (already filled)
[9/50] SKIP (already filled)
[10/50] SKIP (already filled)
[11/50] SKIP (already filled)
[12/50] SKIP (already filled)
[13/50] SKIP (already filled)
[14/50] SKIP (already filled)
[15/50] SKIP (already filled)
[16/50] SKIP (already filled)
[17/50] SKIP (already filled)
[18/50] SKIP (already filled)
[19/50] SKIP (already filled)
[20/50] SKIP (already filled)
[21/50] SKIP (already filled)
[22/50] SKIP (already filled)
[23/50] SKIP (already filled)
[24/50] SKIP (already filled)
[25/50] SKIP (already filled)
[26/50] SKIP (already filled)
[27/50] SKIP (already filled)
[28/50] SKIP (already filled)
[29/50] SKIP (already filled)

[30/50] What are the specific conditions, time limits, and late payment interest rate ca...
  ✓ Answer: To revive a discontinued policy, the policyholder must meet specific conditions, adhere to time limi...
  ✓ Triplets: 30 used

[31/50] What is the exact waiting period specified in this document before a policyholde...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[32/50] How much additional loyalty bonus is paid directly to the policyholder if they m...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[33/50] Under what circumstances can a policyholder request a partial withdrawal from th...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[34/50] Which specific international stock market index is used to determine the Special...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[35/50] What is the maximum age limit up to which a policyholder can add an accidental d...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[36/50] How does the policy document define the 'Guaranteed Income Benefit' that is paid...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[37/50] What is the administrative fee and refund policy if a customer decides to cancel...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[38/50] How many free comprehensive medical examinations is the policyholder entitled to...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[39/50] Which specific third-party digital payment apps, such as Paytm or PhonePe, are e...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[40/50] What is the dynamic equity asset allocation ratio used by the fund manager to in...
  ✓ Answer: ⚠️ The requested information was not found in the knowledge graph. The graph may not contain this sp...
  ✓ Triplets: 30 used

[41/50] I just got my policy document yesterday but I changed my mind and want to cancel...
  ✓ Answer: To address your question, we need to examine the relationships related to policy cancellation and re...
  ✓ Triplets: 30 used

[42/50] I missed my monthly premium payment date because I was traveling. Will my life c...
  ✓ Answer: To determine if your life cover will stop immediately or if you have extra time to pay, we need to e...
  ✓ Triplets: 30 used

[43/50] My policy has been in a reduced 'paid-up' state for the last two years. Will I s...
  ✓ Answer: Based on the knowledge graph triplets, a paid-up policy is not entitled to future reversionary bonus...
  ✓ Triplets: 30 used

[44/50] I am facing a financial emergency and need some quick cash. Can I get a loan fro...
  ✓ Answer: You can get a loan from your policy. The amount you can borrow is limited to the surrender value of ...
  ✓ Triplets: 30 used

[45/50] I paid my renewal premium by cheque, but it was returned due to insufficient fun...
  ✓ Answer: To address your situation, we need to understand the implications of a returned cheque due to insuff...
  ✓ Triplets: 30 used

[46/50] My insurance agent offered to collect my renewal premium in cash. Is it okay to ...
  ✓ Answer: According to the knowledge graph, there is no direct relationship that explicitly states it is okay ...
  ✓ Triplets: 30 used

[47/50] I have lost my original policy bond. Is there a way to get a new one, and will i...
  ✓ Answer: To address your concern about losing the original policy bond, we can refer to triplet [2] which men...
  ✓ Triplets: 30 used

[48/50] I want to transfer my policy to my brother as a gift. What is the process for do...
  ✓ Answer: To transfer your policy to your brother as a gift, you need to follow the process outlined in the kn...
  ✓ Triplets: 30 used

[49/50] I want to name my 12-year-old daughter as my policy beneficiary. What extra step...
  ✓ Answer: To name your 12-year-old daughter as your policy beneficiary, you need to consider that she is a min...
  ✓ Triplets: 30 used

[50/50] If I am unhappy with how the insurance company's grievance officer resolved my c...
  ✓ Answer: If you are unhappy with how the insurance company's grievance officer resolved your complaint, you c...
  ✓ Triplets: 30 used

============================================================
  ✓ Done! Skipped: 29, Newly filled: 21
  ✓ Saved to CSV
============================================================

In [12]:
# ============================================================
# Cell 3: Fill hybridRAG_answer & hybridRAG_sources
# ============================================================
# ► Skips rows that already have hybridRAG_answer filled.
# ► Saves CSV after EACH question.
# ► Requires vectorRAG_answer & graphRAG_answer to be filled first.

df = pd.read_csv(CSV_PATH)

print('=' * 60)
print('  Filling: hybridRAG_answer & hybridRAG_sources')
print('=' * 60)

skipped = 0
filled  = 0

for idx, row in df.iterrows():
    question = row['question']
    
    # --- SKIP if already filled ---
    if not is_empty(row.get('hybridRAG_answer')):
        skipped += 1
        print(f'[{idx+1}/{len(df)}] SKIP (already filled)')
        continue
    
    vector_answer = str(row.get('vectorRAG_answer', '') or '')
    graph_answer  = str(row.get('graphRAG_answer', '') or '')
    
    print(f'\n[{idx+1}/{len(df)}] {question[:80]}...')
    
    try:
        resp = requests.post(
            f'{HYBRID_API}/api/hybrid/compose',
            json={
                'query': question,
                'vector_answer': vector_answer,
                'graph_answer': graph_answer,
            },
            timeout=120
        )
        resp.raise_for_status()
        data = resp.json()
        
        df.at[idx, 'hybridRAG_answer'] = data.get('answer', '')
        
        # Hybrid sources = combination of vector sources + graph triplets
        vector_sources_str = str(row.get('vectorRAG_sources', '[]') or '[]')
        graph_triplets_str = str(row.get('graphRAG_triplets', '[]') or '[]')
        
        try:
            v_sources = json.loads(vector_sources_str)
        except:
            v_sources = []
        try:
            g_triplets = json.loads(graph_triplets_str)
        except:
            g_triplets = []
        
        hybrid_sources = {
            'vector_sources': v_sources,
            'graph_triplets': g_triplets
        }
        df.at[idx, 'hybridRAG_sources'] = json.dumps(hybrid_sources)
        
        print(f'  ✓ Answer: {data["answer"][:100]}...')
        filled += 1
        
    except Exception as e:
        print(f'  ✗ ERROR: {e}')
        print(f'  ⚠ Stopping here. Change API key if needed and re-run this cell.')
        df.to_csv(CSV_PATH, index=False)
        raise
    
    # --- SAVE after each question ---
    df.to_csv(CSV_PATH, index=False)
    time.sleep(1)

print(f'\n{"=" * 60}')
print(f'  ✓ Done! Skipped: {skipped}, Newly filled: {filled}')
print(f'  ✓ Saved to CSV')
print('=' * 60)

============================================================
  Filling: hybridRAG_answer & hybridRAG_sources
============================================================

[1/50] What is the unique identification number (UIN) of the ICICI Pru Future Perfect p...

C:\Users\grove\AppData\Local\Temp\ipykernel_32788\1209779836.py:44: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'The unique identification number (UIN) of the ICICI Pru Future Perfect policy is 105N153V04.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, 'hybridRAG_answer'] = data.get('answer', '')
C:\Users\grove\AppData\Local\Temp\ipykernel_32788\1209779836.py:63: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '{"vector_sources": [{"text": "later  of  Policy  Issue  Date  or  Policy  Acceptance  Date. 6.Date  of\nDiscontinuance of the Policy means the due date of the first unpaid\npremium. 7.Date of Maturity means the date specified in the Policy\nSchedule on which the Policy Term ends and the Maturity benefit, if\napplicable, is payable. 8.Death Benefit means the benefit, which is\npayable  on  death  of  the  Life  Assured  during  the  Policy  Term  as\nspecified in the Policy document. 9.Fully paid policy is a policy for\nwhich all premiums have been paid, as per the Premium Payment\nTerm selected, and no further premiums are due.  10.Guaranteed\nMaturity Benefit means the amount specified in the Policy Schedule\nthat is guaranteed to be paid by Us in accordance with the terms of\nthe Policy. 11.Life Assured is the person named in the Policy Schedule\non whose life the Policy has been issued. 12.Maturity Benefit means\nthe benefit , if any, which is payable on the Date of Maturity as", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 1, "chunk_index": 1, "page_chunk_index": 1}, "score": 0.1159}, {"text": "Policy Document - Terms and Conditions of your policy\nICICI Pru Future Perfect\nUIN:105N153V04-A Participating Non-Linked Life Individual Savings\nProduct \nPART-B\nDefinitions\n1.Age means age of the Life Assured in completed years as on the\ndate of commencement of risk of policy .  2.Annualised Premium\nmeans the premium amount payable in a Policy Year excluding the\ntaxes, rider premiums, underwriting extra premiums and loadings for\nmodal premiums. 3.Appointee means the person appointed by You to\nreceive the benefits payable under the Policy till Your Nominee is a\nminor. 4.Claimant  means the person entitled to receive the Policy\nbenefits and includes the policyholder, the nominee, the assignee, the\nlegal heir, the legal representative(s) or the holder(s) of succession\ncertificate as the case may be. 5.Date of commencement of risk is\nlater  of  Policy  Issue  Date  or  Policy  Acceptance  Date. 6.Date  of\nDiscontinuance of the Policy means the due date of the first unpaid", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 1, "chunk_index": 0, "page_chunk_index": 0}, "score": 0.1148}, {"text": "Please refer to Appendix III for details on this section. The Policy is\nsubject  to  the  terms  and  conditions  as  mentioned  in  the  Policy\ndocument and is governed by the Laws of India.\n6.Communication address Our communication address is:  Address:\nCustomer Service Desk\nICICI Prudential Life Insurance Company\nLimited,  Unit  No.  901A,  901B,  1001A  &  1002B,  Prism  Towers,\nMindspace,\n \nLink\n \nRoad,\n \nGoregaon\n \n(West), Mumbai-\n400104. Maharashtra. Telephone:  1800-2660 Facsimile:  022  4205\n8222  E-mail:  lifeline@iciciprulife.com We expect You to immediately\ninform Us about any change in Your address or contact details. \n7.Electronic transactions All transactions carried out by You through\nInternet,  electronic,  call  centres,  tele-service  operations,  computer,\nautomated  machines  network  or  through  other  means  of\ncommunication will be valid and legally binding on Us as well as\nYou. This will be subject to the relevant guidelines and terms and", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 3, "chunk_index": 31, "page_chunk_index": 9}, "score": 0.1109}, {"text": "Insurance  Ombudsman.  We  request  You  to  regularly  check  our\nwebsite  at www.iciciprulife.com or  the  website  of  the  IRDAI\nat www.irdai.gov.in for updated contact details.\n1.  AHMEDABAD: Office  of  the  Insurance  Ombudsman,  Jeevan\nPrakash  Building,  6th  floor,  Tilak  Marg,  Relief  Road,  Ahmedabad\n-380\n \n001\n \nTel:\n \n079\n \n-\n \n25501201/02/05/06\n \nEmail:\nbimalokpal.ahmedabad@cioins.co.in  Areas of Jurisdiction: Gujarat ,\nDadra & Nagar Haveli, Daman and Diu\n2. BENGALURU: Office of Insurance Ombudsman, Jeevan Soudha\nBuilding, PID No. 57-27-N-19, Ground Floor, 19/19, 24th Main Road,\nJP Nagar, 1st Phase, Bengaluru \u2013 560078 Tel: 080 - 26652048 /\n26652049  Email:  bimalokpal.bengaluru@cioins.co.in\n Areas  of\nJurisdiction: Karnataka\n3. BHOPAL: Office of the Insurance Ombudsman, 1 st floor, \u201cJeevan\nShikha\u201d, 60-B, Hoshangabad Road, Opp. Gayatri Mandir, Bhopal \u2013\n462011.  Tel:  0755-2769201,  2769202  and  2769203  Email:\nbimalokpal.bhopal@cioins.co.in\n Areas  of  Jurisdiction:", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 5, "chunk_index": 48, "page_chunk_index": 3}, "score": 0.1104}, {"text": "or  Company  means  ICICI  Prudential  Life  Insurance  Company\nLimited.\nPART-C\n1.Benefits payable:\n1.Death Benefit\ni. On death of the Life Assured during the Policy Term, for a Premium\nPaying or Fully Paid Policy, the following will be payable:  Death\nBenefit = Higher of (A,B), Where, A = Sum Assured on Death, plus\nsubsisting  bonuses*  already  accrued,  plus  accrued  Guaranteed\nAdditions B  =  105%  of  total  premiums  received  till  the  date  of\ndeath Sum  Assured  on  Death  is  defined  as,  highest  of \u2022  10  X\nAnnualised Premium \u2022 Guaranteed Maturity Benefit (GMB) *Bonuses\nconsist of accrued reversionary bonuses, interim bonus and terminal\nbonus,  if  declared. For  policies  issued  on  minor  life,  Date  of\ncommencement  of  risk  is  later  of  Policy  Issue  Date  or  Policy\nAcceptance  Date. ii.  On  payment  of  Death  Benefit  the  policy  will\nterminate and all rights, benefits and interests under the policy will", "metadata": {"source_file": "4ec93fc12bff.pdf", "page_number": 1, "chunk_index": 7, "page_chunk_index": 7}, "score": 0.1097}], "graph_triplets": [{"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "HAS_ADDRESS", "relation_props": {"source_page": 4, "source_chunk": 39, "confidence": 1.0}, "object": "Unit No. 901A, 901B, 1001A & 1002B, Prism Towers, Mindspace, Link Road, Goregaon (West), Mumbai- 400104. Maharashtra.", "object_type": "LOCATION", "object_props": {}, "source_page": 4, "rerank_score": -1.4520355463027954}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "HAS_COMMUNICATION_ADDRESS", "relation_props": {"source_page": 3, "source_chunk": 31, "confidence": 0.95}, "object": "Customer Service Desk", "object_type": "DEPARTMENT", "object_props": {}, "source_page": 3, "rerank_score": -4.119099140167236}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "IS_REFERRED_TO_AS", "relation_props": {"source_page": 1, "source_chunk": 6, "confidence": 1.0}, "object": "We", "object_type": "COMPANY", "object_props": {}, "source_page": 1, "rerank_score": -4.163426399230957}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "UNAUTHORIZED_TO", "relation_props": {"source_page": 2, "source_chunk": 15, "confidence": 0.95}, "object": "person or individual or entity", "object_type": "THIRD PARTY", "object_props": {}, "source_page": 2, "rerank_score": -4.167984962463379}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "AUTHORIZES", "relation_props": {"source_page": 2, "source_chunk": 15, "confidence": 0.9}, "object": "branch offices", "object_type": "OFFICE", "object_props": {}, "source_page": 2, "rerank_score": -4.330297470092773}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "ISSUES", "relation_props": {"source_page": 2, "source_chunk": 15, "confidence": 0.95}, "object": "official printed receipt", "object_type": "RECEIPT", "object_props": {}, "source_page": 2, "rerank_score": -4.332409858703613}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "HAS_POLICYHOLDERS_PROTECTION_DEPARTMENT", "relation_props": {"source_page": 4, "source_chunk": 39, "confidence": 0.95}, "object": "Policyholders\u2019 Protection and Grievance Redressal Department", "object_type": "DEPARTMENT", "object_props": {}, "source_page": 4, "rerank_score": -4.4122314453125}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "LOCATED_AT", "relation_props": {"source_page": 4, "source_chunk": 39, "confidence": 0.9}, "object": "Policyholders\u2019 Protection and Grievance Redressal Department", "object_type": "DEPARTMENT", "object_props": {}, "source_page": 4, "rerank_score": -4.4171857833862305}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "EXPECTED_TO_INFORM", "relation_props": {"source_page": 3, "source_chunk": 31, "confidence": 0.95}, "object": "You", "object_type": "POLICYHOLDER", "object_props": {}, "source_page": 3, "rerank_score": -4.446688652038574}, {"subject": "ICICI Prulife", "subject_type": "INSURANCE COMPANY", "subject_props": {}, "predicate": "PROVIDES", "relation_props": {"source_page": 4, "source_chunk": 38, "confidence": 0.95}, "object": "customer support", "object_type": "SERVICE", "object_props": {}, "source_page": 4, "rerank_score": -4.48253059387207}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "LOCATED_AT", "relation_props": {"source_page": 4, "source_chunk": 39, "confidence": 0.9}, "object": "Grievance Redressal Committee", "object_type": "COMMITTEE", "object_props": {}, "source_page": 4, "rerank_score": -4.5393967628479}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "DRAWN_IN_FAVOUR_OF", "relation_props": {"source_page": 2, "source_chunk": 15, "confidence": 0.95}, "object": "cheque or demand draft", "object_type": "PAYMENT INSTRUMENT", "object_props": {}, "source_page": 2, "rerank_score": -4.877981185913086}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "DEFINES", "relation_props": {"source_page": 1, "source_chunk": 7, "confidence": 0.95}, "object": "Death Benefit", "object_type": "BENEFIT", "object_props": {}, "source_page": 1, "rerank_score": -4.953701972961426}, {"subject": "ICICI Prudential Life Insurance Company Limited", "subject_type": "COMPANY", "subject_props": {}, "predicate": "HAS_GRIEVANCE_REDRESSAL_COMMITTEE", "relation_props": {"source_page": 4, "source_chunk": 39, "confidence": 0.95}, "object": "Grievance Redressal Committee", "object_type": "COMMITTEE", "object_props": {}, "source_page": 4, "rerank_score": -4.958623886108398}, {"subject": "Policyholders\u2019 Protection and Grievance Redressal Department", "subject_type": "DEPARTMENT", "subject_props": {}, "predicate": "LOCATED_AT", "relation_props": {"source_page": 4, "source_chunk": 39, "confidence": 0.9}, "object": "ICICI Prudential Life Insurance Company Limited", "object_type": "COMPANY", "object_props": {}, "source_page": 4, "rerank_score": -5.057755470275879}, {"subject": "ICICI Prulife", "subject_type": "INSURANCE COMPANY", "subject_props": {}, "predicate": "HAS", "relation_props": {"source_page": 4, "source_chunk": 38, "confidence": 0.95}, "object": "customer service desk", "object_type": "PHYSICAL LOCATION", "object_props": {}, "source_page": 4, "rerank_score": -5.244355201721191}, {"subject": "Policyholders\u2019 Protection and Grievance Redressal Department", "subject_type": "DEPARTMENT", "subject_props": {}, "predicate": "HAS_POLICYHOLDERS_PROTECTION_DEPARTMENT", "relation_props": {"source_page": 4, "source_chunk": 39, "confidence": 0.95}, "object": "ICICI Prudential Life Insurance Company Limited", "object_type": "COMPANY", "object_props": {}, "source_page": 4, "rerank_score": -5.4088640213012695}, {"subject": "ICICI Prudential Life Insurance", "subject_type": "INSURANCE COMPANY", "subject_props": {}, "predicate": "REQUESTS_REGULAR_CHECK_OF", "relation_props": {"source_page": 5, "source_chunk": 48, "confidence": 0.95}, "object": "IRDAI website", "object_type": "REGULATORY WEBSITE", "object_props": {}, "source_page": 5, "rerank_score": -5.427366733551025}, {"subject": "ICICI Prulife", "subject_type": "INSURANCE COMPANY", "subject_props": {}, "predicate": "HAS", "relation_props": {"source_page": 4, "source_chunk": 38, "confidence": 0.95}, "object": "branches", "object_type": "PHYSICAL LOCATION", "object_props": {}, "source_page": 4, "rerank_score": -5.666873931884766}, {"subject": "ICICI Prudential Life", "subject_type": "INSURANCE COMPANY", "subject_props": {}, "predicate": "REQUESTS_REGULAR_CHECKING_OF", "relation_props": {"source_page": 5, "source_chunk": 47, "confidence": 0.8}, "object": "Website", "object_type": "PLATFORM", "object_props": {}, "source_page": 5, "rerank_score": -5.913726329803467}, {"subject": "ICICI Prulife", "subject_type": "INSURANCE COMPANY", "subject_props": {}, "predicate": "APPOINTS", "relation_props": {"source_page": 4, "source_chunk": 38, "confidence": 0.95}, "object": "Grievance Redressal Officer", "object_type": "ROLE", "object_props": {}, "source_page": 4, "rerank_score": -6.070096015930176}, {"subject": "ICICI Prudential Life", "subject_type": "INSURANCE COMPANY", "subject_props": {}, "predicate": "REQUESTS_REGULAR_CHECKING_OF", "relation_props": {"source_page": 5, "source_chunk": 47, "confidence": 0.8}, "object": "IRDAI Website", "object_type": "REGULATORY WEBSITE", "object_props": {}, "source_page": 5, "rerank_score": -6.258805274963379}, {"subject": "policy number", "subject_type": "POLICY IDENTIFIER", "subject_props": {}, "predicate": "MUST_MENTION", "relation_props": {"source_page": 2, "source_chunk": 15, "confidence": 0.9}, "object": "policyholder", "object_type": "CUSTOMER", "object_props": {}, "source_page": 2, "rerank_score": -7.498225212097168}, {"subject": "policyholder", "subject_type": "CUSTOMER", "subject_props": {}, "predicate": "MUST_MENTION", "relation_props": {"source_page": 2, "source_chunk": 15, "confidence": 0.9}, "object": "policy number", "object_type": "POLICY IDENTIFIER", "object_props": {}, "source_page": 2, "rerank_score": -7.867898941040039}, {"subject": "Policy", "subject_type": "INSURANCE POLICY", "subject_props": {}, "predicate": "IS_ASSIGNED_DURING", "relation_props": {"source_page": 3, "source_chunk": 29, "confidence": 0.95}, "object": "minority of the Life Assured", "object_type": "LIFE EVENT", "object_props": {}, "source_page": 3, "rerank_score": -8.740278244018555}, {"subject": "application number or policy number", "subject_type": "PAYMENT REFERENCE", "subject_props": {}, "predicate": "SHOULD_INCLUDE", "relation_props": {"source_page": 2, "source_chunk": 15, "confidence": 0.9}, "object": "payer", "object_type": "CUSTOMER", "object_props": {}, "source_page": 2, "rerank_score": -8.949563026428223}, {"subject": "Policy", "subject_type": "INSURANCE POLICY", "subject_props": {}, "predicate": "REQUIRES", "relation_props": {"source_page": 4, "source_chunk": 34, "confidence": 0.95}, "object": "Company", "object_type": "ORGANIZATION", "object_props": {}, "source_page": 4, "rerank_score": -8.996854782104492}, {"subject": "Policy", "subject_type": "INSURANCE POLICY", "subject_props": {}, "predicate": "IS_COVERED_BY", "relation_props": {"source_page": 1, "source_chunk": 1, "confidence": 0.95}, "object": "Life Assured", "object_type": "PERSON", "object_props": {}, "source_page": 1, "rerank_score": -9.027427673339844}, {"subject": "Policy", "subject_type": "INSURANCE POLICY", "subject_props": {}, "predicate": "HAS_TOTAL_PREMIUMS_PAID", "relation_props": {"source_page": 1, "source_chunk": 6, "confidence": 1.0}, "object": "Total Premiums Paid", "object_type": "MONETARY VALUE", "object_props": {}, "source_page": 1, "rerank_score": -9.082747459411621}, {"subject": "Policy", "subject_type": "INSURANCE POLICY", "subject_props": {}, "predicate": "IS_TYPE_OF", "relation_props": {"source_page": 1, "source_chunk": 4, "confidence": 0.95}, "object": "Premium Paying policy", "object_type": "POLICY TYPE", "object_props": {}, "source_page": 1, "rerank_score": -9.098968505859375}]}' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, 'hybridRAG_sources'] = json.dumps(hybrid_sources)

  ✓ Answer: The unique identification number (UIN) of the ICICI Pru Future Perfect policy is 105N153V04....

[2/50] How does the policy document define 'Age' under Part-B?...
  ✓ Answer: According to the policy document, 'Age' under Part-B is defined as the age of the Life Assured in co...

[3/50] What is the grace period allowed for a policyholder who has chosen a monthly pre...
  ✓ Answer: The grace period allowed for a policyholder who has chosen a monthly premium frequency is 15 days fo...

[4/50] Where is the physical communication address of the ICICI Prudential Life Insuran...
  ✓ Answer: The physical communication address of the ICICI Prudential Life Insurance Customer Service Desk is l...

[5/50] After how many years from the date of policy issuance, risk commencement, reviva...
  ✓ Answer: A life insurance policy cannot be questioned on any ground whatsoever after 3 years from the date of...

[6/50] What are the three authorized frequencies for premium payments under this policy...
  ✓ Answer: The three authorized frequencies for premium payments under this policy are Yearly, Half-yearly, and...

[7/50] How much does the company charge for issuing a duplicate copy of the policy docu...
  ✓ Answer: The company charges ₹ 200 for issuing a duplicate copy of the policy document....

[8/50] Who is defined as an 'Appointee' under Part-B of this policy?...
  ✓ Answer: An 'Appointee' is defined as the person appointed by You to receive the benefits payable under the P...

[9/50] To which parties can benefits be legally payable according to Part-D Section 9 o...
  ✓ Answer: Benefits can be payable to the policyholder, assignee(s), and the life assured. In the event of the ...

[10/50] What is the maximum compensation limit that the Insurance Ombudsman can award un...
  ✓ Answer: The maximum compensation limit that the Insurance Ombudsman can award is Rupees Fifty Lakhs, includi...

[11/50] If a policyholder opts for a monthly premium payment mode, what loading percenta...
  ✓ Answer: If a policyholder opts for a monthly premium payment mode, a loading percentage of 4.5% is applied t...

[12/50] What is the Guaranteed Surrender Value (GSV) factor for a policy surrendered dur...
  ✓ Answer: The Guaranteed Surrender Value (GSV) factor for a policy surrendered during its third policy year is...

[13/50] For a policy with a Premium Payment Term of 10 years, what is the Guaranteed Add...
  ✓ Answer: The Guaranteed Additions (GAs) rate for policy years 11 to 15 for a policy with a Premium Payment Te...

[14/50] What was the specific policy loan interest rate applicable in September 2025, an...
  ✓ Answer: The specific policy loan interest rate applicable in September 2025 was 8.00% per year. It is compou...

[15/50] What is the mathematical formula used to calculate the Paid-up Guaranteed Maturi...
  ✓ Answer: The mathematical formula used to calculate the Paid-up Guaranteed Maturity Benefit (Paid-up GMB) is:...

[16/50] What is the maximum percentage of the Surrender Value that a policyholder can bo...
  ✓ Answer: The maximum percentage of the Surrender Value that a policyholder can borrow as a loan is up to 80% ...

[17/50] If the 10-year Government Securities yield is sourced at 6.50%, what will be the...
  ✓ Answer: If the 10-year Government Securities yield is 6.50%, the applicable policy loan interest rate would ...

[18/50] How is the Death Benefit 'B' calculated under Part-C?...
  ✓ Answer: The Death Benefit 'B' is calculated as 105% of total premiums received till the date of death under ...

[19/50] Write out the full mathematical formula for calculating the Guaranteed Surrender...
  ✓ Answer: The full mathematical formula for calculating the Guaranteed Surrender Value (GSV) is: GSV = GSV Fac...

[20/50] Using the formula for policy years 8 to (Policy Term less 2), calculate the GSV ...
  ✓ Answer: To calculate the GSV factor for policy year 10 when the total policy term is 15 years, we find that ...

[21/50] How does converting a policy to 'paid-up' status affect future reversionary bonu...
  ✓ Answer: Converting a policy to 'paid-up' status means it will not be entitled to future reversionary bonuses...

[22/50] Compare the foreclosure rules for an active/fully paid policy with those for a p...
  ✓ Answer: For an active or fully paid policy, the policy cannot be foreclosed if a loan is outstanding and the...

[23/50] What additional documents are required to process a death claim for an unnatural...
  ✓ Answer: To process a death claim for an unnatural death, you need to provide additional documents compared t...

[24/50] Explain the vesting rules when a policy is taken on a minor's life, including wh...
  ✓ Answer: When a policy is taken on a minor's life, it will vest on them when they turn 18. At this point, the...

[25/50] What is the general rule regarding a registered nomination when a policy is assi...
  ✓ Answer: When a policy is assigned under Section 38, the general rule is that a registered nomination will au...

[26/50] If a policyholder commits suicide, how does the payout structure change if it ha...
  ✓ Answer: If a policyholder commits suicide within 12 months of risk commencement or within 12 months of a pol...

[27/50] How is the policy loan interest rate calculated, how frequently is it reviewed, ...
  ✓ Answer: The policy loan interest rate is calculated as 150 basis points in addition to the prevailing yield ...

[28/50] Under Section 38, what are the four grounds on which an insurer can decline to a...
  ✓ Answer: Under Section 38, an insurer can decline to act on a policy transfer on four grounds: if the transfe...

[29/50] How does the grace period differ across premium frequencies, and what happens to...
  ✓ Answer: The grace period for paying premiums differs based on how often you pay. If you pay monthly, you hav...

[30/50] What are the specific conditions, time limits, and late payment interest rate ca...
  ✓ Answer: To revive a discontinued policy, the policyholder must meet certain conditions within 5 years from t...

[31/50] What is the exact waiting period specified in this document before a policyholde...
  ✓ Answer: I cannot find the answer in the document. The document does not specify the waiting period for claim...

[32/50] How much additional loyalty bonus is paid directly to the policyholder if they m...
  ✓ Answer: I cannot find the answer in the document. The information about an additional loyalty bonus paid dir...

[33/50] Under what circumstances can a policyholder request a partial withdrawal from th...
  ✓ Answer: I cannot find the answer in the document. The information about requesting a partial withdrawal from...

[34/50] Which specific international stock market index is used to determine the Special...
  ✓ Answer: The specific international stock market index used to determine the Special Surrender Value (SSV) ca...

[35/50] What is the maximum age limit up to which a policyholder can add an accidental d...
  ✓ Answer: I cannot find the answer in the document....

[36/50] How does the policy document define the 'Guaranteed Income Benefit' that is paid...
  ✓ Answer: The policy document does not contain information about the 'Guaranteed Income Benefit' paid out annu...

[37/50] What is the administrative fee and refund policy if a customer decides to cancel...
  ✓ Answer: The administrative fee for cancelling a policy after the 30-day Free Look period has passed is not s...

[38/50] How many free comprehensive medical examinations is the policyholder entitled to...
  ✓ Answer: I cannot find the answer in the document....

[39/50] Which specific third-party digital payment apps, such as Paytm or PhonePe, are e...
  ✓ Answer: The specific third-party digital payment apps, such as Paytm or PhonePe, are not explicitly listed i...

[40/50] What is the dynamic equity asset allocation ratio used by the fund manager to in...
  ✓ Answer: I cannot find the answer in the document. The information about the dynamic equity asset allocation ...

[41/50] I just got my policy document yesterday but I changed my mind and want to cancel...
  ✓ Answer: You can cancel your policy within 30 days from the date you received it. To do this, you need to ret...

[42/50] I missed my monthly premium payment date because I was traveling. Will my life c...
  ✓ Answer: You will not lose your life cover immediately if you miss a monthly premium payment. You have a grac...

[43/50] My policy has been in a reduced 'paid-up' state for the last two years. Will I s...
  ✓ Answer: You will not receive the annual reversionary bonuses declared by the company because a paid-up polic...

[44/50] I am facing a financial emergency and need some quick cash. Can I get a loan fro...
  ✓ Answer: You can get a loan from your policy if it has a surrender value. The loan amount is limited to up to...

[45/50] I paid my renewal premium by cheque, but it was returned due to insufficient fun...
  ✓ Answer: Having a payment slip is not enough to guarantee you are safe if your cheque was returned due to ins...

[46/50] My insurance agent offered to collect my renewal premium in cash. Is it okay to ...
  ✓ Answer: It's not okay to pay your insurance agent directly in cash for your renewal premium. The document st...

[47/50] I have lost my original policy bond. Is there a way to get a new one, and will i...
  ✓ Answer: You can get a new policy bond as a duplicate by submitting a written request with the necessary docu...

[48/50] I want to transfer my policy to my brother as a gift. What is the process for do...
  ✓ Answer: To transfer your policy to your brother as a gift, you need to assign or transfer the policy accordi...

[49/50] I want to name my 12-year-old daughter as my policy beneficiary. What extra step...
  ✓ Answer: To name your 12-year-old daughter as your policy beneficiary, you need to appoint a person to receiv...

[50/50] If I am unhappy with how the insurance company's grievance officer resolved my c...
  ✓ Answer: If you are unhappy with how the insurance company's grievance officer resolved your complaint, you c...

============================================================
  ✓ Done! Skipped: 0, Newly filled: 50
  ✓ Saved to CSV
============================================================

In [13]:
# ============================================================
# Cell 4: Setup RAGAS evaluation (LLM + Embeddings)
# ============================================================
# This cell configures the LLM and EMBEDDINGS for RAGAS.
# ► answer_relevancy REQUIRES embeddings — without this it returns NaN.
# ► Re-run this cell after changing the API key in .env.

# !pip install ragas langchain-openai langchain-community datasets

import os
from dotenv import load_dotenv

# Load .env from project root (override=True to pick up new keys)
env_path = os.path.join(os.path.dirname(os.path.abspath('__file__')), '..', '.env')
load_dotenv(dotenv_path=env_path, override=True)

OPENAI_API_KEY = os.getenv('OPEN_API_KEY') or os.getenv('OPENAI_API_KEY')
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

print(f'OpenAI API Key loaded: {"Yes" if OPENAI_API_KEY else "No"}')
print(f'Key prefix: {OPENAI_API_KEY[:20]}...' if OPENAI_API_KEY else 'NOT SET')

# --- Setup LLM + Embeddings for RAGAS ---
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

ragas_llm = LangchainLLMWrapper(ChatOpenAI(
    model='gpt-4o',
    api_key=OPENAI_API_KEY,
    temperature=0,
))

ragas_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(
    model='text-embedding-3-small',
    api_key=OPENAI_API_KEY,
))

print('\n✓ RAGAS LLM configured:        gpt-4o')
print('✓ RAGAS Embeddings configured:  text-embedding-3-small')
print('\nTip: If you change the API key in .env, re-run this cell to reload it.')

OpenAI API Key loaded: Yes
Key prefix: sk-proj-Jh16sKomVbMT...

c:\Users\grove\miniconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\grove\miniconda3\Lib\site-packages\instructor\providers\gemini\client.py:5: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai  # type: ignore[import-not-found]
C:\Users\grove\AppData\Local\Temp\ipykernel_32788\1965011540.py:28: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  ragas_llm = LangchainLLMWrapper(ChatOpenAI(

✓ RAGAS LLM configured:        gpt-4o
✓ RAGAS Embeddings configured:  text-embedding-3-small

Tip: If you change the API key in .env, re-run this cell to reload it.

C:\Users\grove\AppData\Local\Temp\ipykernel_32788\1965011540.py:34: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  ragas_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(

In [14]:
# ============================================================
# Cell 5: RAGAS helper functions
# ============================================================

from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)
from datasets import Dataset


def batch_ragas_evaluate(questions, answers, contexts_list, ground_truths):
    """
    Batch-evaluate RAGAS metrics for multiple questions at once.
    This is MUCH faster than calling evaluate() per question
    because it parallelizes LLM calls internally.
    
    Returns:
        List of dicts, one per question, with keys:
        faithfulness, answer_relevancy, context_precision, context_recall
    """
    # Sanitize inputs
    clean_contexts = []
    for ctx in contexts_list:
        if not ctx:
            clean_contexts.append(['No context retrieved.'])
        else:
            clean_contexts.append(ctx)
    
    data = {
        'question': questions,
        'answer': answers,
        'contexts': clean_contexts,
        'ground_truth': ground_truths,
    }
    
    dataset = Dataset.from_dict(data)
    
    result = evaluate(
        dataset,
        metrics=[faithfulness, answer_relevancy, context_precision, context_recall],
        llm=ragas_llm,
        embeddings=ragas_embeddings,
    )
    
    # Convert result to per-row dicts
    result_df = result.to_pandas()
    per_row = []
    for _, row in result_df.iterrows():
        per_row.append({
            'faithfulness': row.get('faithfulness'),
            'answer_relevancy': row.get('answer_relevancy'),
            'context_precision': row.get('context_precision'),
            'context_recall': row.get('context_recall'),
        })
    return per_row


def extract_context_texts_from_sources(sources_json_str: str) -> list:
    """Extract plain text contexts from vectorRAG sources JSON."""
    try:
        sources = json.loads(str(sources_json_str))
        if isinstance(sources, list):
            return [s.get('text', '') for s in sources if s.get('text')]
    except:
        pass
    return []


def extract_context_texts_from_triplets(triplets_json_str: str) -> list:
    """Convert graphRAG triplets to plain text contexts."""
    try:
        triplets = json.loads(str(triplets_json_str))
        if isinstance(triplets, list):
            texts = []
            for t in triplets:
                subj = t.get('subject', '?')
                pred = t.get('predicate', '?').replace('_', ' ').lower()
                obj  = t.get('object', '?')
                texts.append(f'{subj} {pred} {obj}')
            return texts if texts else []
    except:
        pass
    return []


def extract_context_texts_from_hybrid(hybrid_json_str: str) -> list:
    """Extract combined contexts from hybridRAG sources JSON."""
    try:
        hybrid = json.loads(str(hybrid_json_str))
        contexts = []
        for s in hybrid.get('vector_sources', []):
            if s.get('text'):
                contexts.append(s['text'])
        for t in hybrid.get('graph_triplets', []):
            subj = t.get('subject', '?')
            pred = t.get('predicate', '?').replace('_', ' ').lower()
            obj  = t.get('object', '?')
            contexts.append(f'{subj} {pred} {obj}')
        return contexts if contexts else []
    except:
        pass
    return []


print('✓ RAGAS helper functions defined (batch mode).')

✓ RAGAS helper functions defined (batch mode).

C:\Users\grove\AppData\Local\Temp\ipykernel_32788\3361628844.py:6: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import (
C:\Users\grove\AppData\Local\Temp\ipykernel_32788\3361628844.py:6: DeprecationWarning: Importing answer_relevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_relevancy
  from ragas.metrics import (
C:\Users\grove\AppData\Local\Temp\ipykernel_32788\3361628844.py:6: DeprecationWarning: Importing context_precision from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_precision
  from ragas.metrics import (
C:\Users\grove\AppData\Local\Temp\ipykernel_32788\3361628844.py:6: DeprecationWarning: Importing context_recall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import context_recall
  from ragas.metrics import (

In [15]:
# ============================================================
# Cell 6: Fill VectorRAG RAGAS metrics (BATCH)
# ============================================================
# Columns: vector_faithfulness, vector_answer_relevancy,
#          vector_context_precision, vector_context_recall
#
# ► Collects all unfilled rows → evaluates in ONE batch call.
# ► Much faster than per-question evaluation.
# ► Saves results to CSV after the batch completes.

df = pd.read_csv(CSV_PATH)

print('=' * 60)
print('  Computing RAGAS metrics for VectorRAG (BATCH)')
print('=' * 60)

# Find unfilled rows
unfilled_indices = []
for idx, row in df.iterrows():
    if is_empty(row.get('vector_faithfulness')):
        unfilled_indices.append(idx)
    else:
        print(f'[{idx+1}/{len(df)}] SKIP (already computed)')

if not unfilled_indices:
    print('\n✓ All rows already computed. Nothing to do.')
else:
    print(f'\n→ {len(unfilled_indices)} questions to evaluate (skipped {len(df) - len(unfilled_indices)})')
    
    # Prepare batch data
    questions = []
    answers = []
    contexts_list = []
    ground_truths = []
    
    for idx in unfilled_indices:
        row = df.iloc[idx]
        questions.append(row['question'])
        answers.append(str(row.get('vectorRAG_answer', '') or ''))
        ground_truths.append(str(row.get('ground_truth', '') or ''))
        contexts_list.append(extract_context_texts_from_sources(
            str(row.get('vectorRAG_sources', '[]') or '[]')
        ))
    
    print(f'→ Running batch RAGAS evaluation...')
    t0 = time.time()
    
    try:
        results = batch_ragas_evaluate(questions, answers, contexts_list, ground_truths)
        
        # Write results back
        for i, idx in enumerate(unfilled_indices):
            df.at[idx, 'vector_faithfulness']      = results[i]['faithfulness']
            df.at[idx, 'vector_answer_relevancy']  = results[i]['answer_relevancy']
            df.at[idx, 'vector_context_precision'] = results[i]['context_precision']
            df.at[idx, 'vector_context_recall']    = results[i]['context_recall']
        
        elapsed = time.time() - t0
        df.to_csv(CSV_PATH, index=False)
        print(f'\n✓ Batch complete! {len(unfilled_indices)} questions evaluated in {elapsed:.1f}s')
        print(f'✓ Saved to CSV')
        
    except Exception as e:
        print(f'\n✗ Batch evaluation failed: {e}')
        print(f'⚠ Change API key in .env → re-run Cell 4 → re-run this cell')
        raise

print('=' * 60)

============================================================
  Computing RAGAS metrics for VectorRAG (BATCH)
============================================================

→ 50 questions to evaluate (skipped 0)
→ Running batch RAGAS evaluation...

Evaluating:   0%|          | 0/200 [00:00<?, ?it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   0%|          | 1/200 [00:15<52:37, 15.86s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   1%|          | 2/200 [00:16<23:27,  7.11s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   2%|▏         | 3/200 [00:33<38:01, 11.58s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   3%|▎         | 6/200 [00:34<13:20,  4.13s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   4%|▍         | 9/200 [00:42<10:59,  3.45s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   6%|▌         | 11/200 [00:59<15:47,  5.01s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   8%|▊         | 17/200 [01:11<09:32,  3.13s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  23%|██▎       | 46/200 [03:27<08:32,  3.33s/it]Exception raised in Job[18]: TimeoutError()
Evaluating:  26%|██▋       | 53/200 [04:14<15:14,  6.22s/it]Exception raised in Job[34]: TimeoutError()
Evaluating:  30%|███       | 61/200 [04:58<21:07,  9.12s/it]Exception raised in Job[46]: TimeoutError()
Evaluating:  36%|███▋      | 73/200 [05:51<09:39,  4.56s/it]Exception raised in Job[50]: TimeoutError()
Evaluating:  38%|███▊      | 76/200 [06:09<11:01,  5.34s/it]Exception raised in Job[58]: TimeoutError()
Evaluating:  46%|████▌     | 92/200 [07:50<10:20,  5.75s/it]Exception raised in Job[76]: TimeoutError()
Evaluating:  47%|████▋     | 94/200 [08:06<11:57,  6.77s/it]Exception raised in Job[79]: TimeoutError()
Exception raised in Job[78]: TimeoutError()
Exception raised in Job[83]: TimeoutError()
Evaluating:  49%|████▉     | 98/200 [08:20<07:46,  4.57s/it]Exception raised in Job[86]: TimeoutError()
Evaluating:  53%|█████▎    | 106/200 [08:48<05:58,  3.81s/it]Exception raised in Job[87]: TimeoutError()
Evaluating:  54%|█████▎    | 107/200 [08:49<05:30,  3.55s/it]Exception raised in Job[121]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  54%|█████▍    | 108/200 [08:58<06:24,  4.18s/it]Exception raised in Job[113]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  55%|█████▌    | 110/200 [09:54<17:35, 11.72s/it]Exception raised in Job[94]: TimeoutError()
Exception raised in Job[98]: TimeoutError()
Exception raised in Job[106]: APIConnectionError(Connection error.)
Exception raised in Job[118]: APIConnectionError(Connection error.)
Exception raised in Job[110]: APIConnectionError(Connection error.)
Exception raised in Job[117]: APIConnectionError(Connection error.)
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception raised in Job[129]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  59%|█████▉    | 118/200 [10:10<06:56,  5.08s/it]Exception raised in Job[102]: TimeoutError()
Evaluating:  60%|██████    | 120/200 [10:33<08:44,  6.56s/it]Exception raised in Job[137]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  62%|██████▏   | 123/200 [10:40<06:22,  4.97s/it]Exception raised in Job[133]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  64%|██████▎   | 127/200 [11:10<06:52,  5.65s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception raised in Job[141]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  64%|██████▍   | 129/200 [11:14<05:25,  4.58s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception raised in Job[125]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  65%|██████▌   | 130/200 [11:38<09:04,  7.78s/it]Exception raised in Job[119]: TimeoutError()
Exception raised in Job[120]: TimeoutError()
Exception raised in Job[114]: TimeoutError()
Evaluating:  68%|██████▊   | 135/200 [11:54<05:44,  5.31s/it]Exception raised in Job[122]: TimeoutError()
Evaluating:  68%|██████▊   | 137/200 [11:58<04:44,  4.52s/it]Exception raised in Job[149]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  70%|███████   | 140/200 [12:14<04:36,  4.61s/it]Exception raised in Job[153]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  70%|███████   | 141/200 [12:18<04:23,  4.47s/it]Exception raised in Job[145]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  72%|███████▏  | 143/200 [12:31<05:04,  5.34s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception raised in Job[157]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  74%|███████▍  | 148/200 [12:43<02:41,  3.11s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception raised in Job[161]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  76%|███████▌  | 151/200 [12:53<02:27,  3.01s/it]Exception raised in Job[126]: TimeoutError()
Evaluating:  77%|███████▋  | 154/200 [13:10<03:16,  4.27s/it]Exception raised in Job[169]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  78%|███████▊  | 155/200 [13:19<04:05,  5.46s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception raised in Job[165]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  78%|███████▊  | 156/200 [13:30<05:16,  7.19s/it]Exception raised in Job[138]: TimeoutError()
Evaluating:  80%|████████  | 161/200 [14:10<04:27,  6.85s/it]Exception raised in Job[142]: TimeoutError()
Evaluating:  81%|████████  | 162/200 [14:14<03:54,  6.17s/it]Exception raised in Job[144]: TimeoutError()
Evaluating:  84%|████████▎ | 167/200 [14:46<03:54,  7.10s/it]Exception raised in Job[146]: TimeoutError()
Evaluating:  85%|████████▌ | 170/200 [15:00<02:57,  5.92s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception raised in Job[185]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  86%|████████▋ | 173/200 [15:14<02:23,  5.33s/it]Exception raised in Job[177]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  88%|████████▊ | 175/200 [15:21<01:54,  4.56s/it]Exception raised in Job[189]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  89%|████████▉ | 178/200 [15:30<01:15,  3.45s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Exception raised in Job[173]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  90%|█████████ | 180/200 [15:57<02:44,  8.21s/it]Exception raised in Job[166]: TimeoutError()
Exception raised in Job[168]: TimeoutError()
Evaluating:  92%|█████████▏| 183/200 [16:08<01:38,  5.80s/it]Exception raised in Job[181]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  92%|█████████▏| 184/200 [16:27<02:15,  8.47s/it]Exception raised in Job[170]: TimeoutError()
Exception raised in Job[197]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  93%|█████████▎| 186/200 [17:06<02:56, 12.58s/it]Exception raised in Job[180]: APIConnectionError(Connection error.)
Exception raised in Job[182]: APIConnectionError(Connection error.)
Exception raised in Job[186]: APIConnectionError(Connection error.)
Exception raised in Job[190]: APIConnectionError(Connection error.)
Exception raised in Job[178]: TimeoutError()
Evaluating:  97%|█████████▋| 194/200 [17:15<00:28,  4.82s/it]Exception raised in Job[192]: TimeoutError()
Evaluating:  98%|█████████▊| 195/200 [18:29<01:01, 12.31s/it]Exception raised in Job[193]: TimeoutError()
Evaluating:  98%|█████████▊| 196/200 [18:30<00:42, 10.75s/it]Exception raised in Job[194]: TimeoutError()
Evaluating:  98%|█████████▊| 197/200 [18:43<00:33, 11.12s/it]Exception raised in Job[196]: TimeoutError()
Evaluating:  99%|█████████▉| 198/200 [18:57<00:23, 11.61s/it]Exception raised in Job[198]: TimeoutError()
Evaluating: 100%|█████████▉| 199/200 [19:08<00:11, 11.56s/it]Exception raised in Job[199]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating: 100%|██████████| 200/200 [19:16<00:00,  5.78s/it]

✓ Batch complete! 50 questions evaluated in 1162.6s
✓ Saved to CSV
============================================================

In [16]:
# ============================================================
# Cell 7: Fill GraphRAG RAGAS metrics (BATCH)
# ============================================================
# Columns: graph_faithfulness, graph_answer_relevancy,
#          graph_context_precision, graph_context_recall

df = pd.read_csv(CSV_PATH)

print('=' * 60)
print('  Computing RAGAS metrics for GraphRAG (BATCH)')
print('=' * 60)

# Find unfilled rows
unfilled_indices = []
for idx, row in df.iterrows():
    if is_empty(row.get('graph_faithfulness')):
        unfilled_indices.append(idx)
    else:
        print(f'[{idx+1}/{len(df)}] SKIP (already computed)')

if not unfilled_indices:
    print('\n✓ All rows already computed. Nothing to do.')
else:
    print(f'\n→ {len(unfilled_indices)} questions to evaluate (skipped {len(df) - len(unfilled_indices)})')
    
    questions = []
    answers = []
    contexts_list = []
    ground_truths = []
    
    for idx in unfilled_indices:
        row = df.iloc[idx]
        questions.append(row['question'])
        answers.append(str(row.get('graphRAG_answer', '') or ''))
        ground_truths.append(str(row.get('ground_truth', '') or ''))
        contexts_list.append(extract_context_texts_from_triplets(
            str(row.get('graphRAG_triplets', '[]') or '[]')
        ))
    
    print(f'→ Running batch RAGAS evaluation...')
    t0 = time.time()
    
    try:
        results = batch_ragas_evaluate(questions, answers, contexts_list, ground_truths)
        
        for i, idx in enumerate(unfilled_indices):
            df.at[idx, 'graph_faithfulness']      = results[i]['faithfulness']
            df.at[idx, 'graph_answer_relevancy']  = results[i]['answer_relevancy']
            df.at[idx, 'graph_context_precision'] = results[i]['context_precision']
            df.at[idx, 'graph_context_recall']    = results[i]['context_recall']
        
        elapsed = time.time() - t0
        df.to_csv(CSV_PATH, index=False)
        print(f'\n✓ Batch complete! {len(unfilled_indices)} questions evaluated in {elapsed:.1f}s')
        print(f'✓ Saved to CSV')
        
    except Exception as e:
        print(f'\n✗ Batch evaluation failed: {e}')
        print(f'⚠ Change API key in .env → re-run Cell 4 → re-run this cell')
        raise

print('=' * 60)

============================================================
  Computing RAGAS metrics for GraphRAG (BATCH)
============================================================

→ 50 questions to evaluate (skipped 0)
→ Running batch RAGAS evaluation...

Evaluating:   0%|          | 0/200 [00:00<?, ?it/s]Exception raised in Job[7]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   0%|          | 1/200 [01:25<4:41:55, 85.00s/it]Exception raised in Job[10]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   1%|          | 2/200 [01:56<2:55:54, 53.31s/it]Exception raised in Job[14]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   2%|▏         | 3/200 [01:59<1:39:27, 30.29s/it]Exception raised in Job[4]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   2%|▏         | 4/200 [02:07<1:10:16, 21.51s/it]Exception raised in Job[3]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   2%|▎         | 5/200 [02:07<45:03, 13.86s/it]  Exception raised in Job[12]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   3%|▎         | 6/200 [02:21<45:24, 14.05s/it]Exception raised in Job[0]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   4%|▎         | 7/200 [02:35<44:24, 13.80s/it]Exception raised in Job[15]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   4%|▍         | 8/200 [02:37<32:08, 10.04s/it]Exception raised in Job[5]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   4%|▍         | 9/200 [02:38<23:10,  7.28s/it]Exception raised in Job[9]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   5%|▌         | 10/200 [02:39<16:55,  5.35s/it]Exception raised in Job[1]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   6%|▌         | 11/200 [02:41<14:05,  4.47s/it]Exception raised in Job[13]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   6%|▌         | 12/200 [02:43<11:35,  3.70s/it]Exception raised in Job[2]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   6%|▋         | 13/200 [02:53<17:27,  5.60s/it]Exception raised in Job[6]: TimeoutError()
Evaluating:   7%|▋         | 14/200 [03:00<18:02,  5.82s/it]Exception raised in Job[11]: TimeoutError()
Exception raised in Job[8]: TimeoutError()
Exception raised in Job[16]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   8%|▊         | 17/200 [03:47<35:01, 11.48s/it]Exception raised in Job[17]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   9%|▉         | 18/200 [03:58<34:39, 11.42s/it]Exception raised in Job[18]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  10%|▉         | 19/200 [04:10<34:45, 11.52s/it]Exception raised in Job[20]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  10%|█         | 20/200 [04:28<38:56, 12.98s/it]Exception raised in Job[26]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  10%|█         | 21/200 [04:52<47:35, 15.95s/it]Exception raised in Job[31]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  11%|█         | 22/200 [04:59<39:51, 13.44s/it]Exception raised in Job[28]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  12%|█▏        | 23/200 [05:00<29:45, 10.09s/it]Exception raised in Job[21]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  12%|█▏        | 24/200 [05:02<22:45,  7.76s/it]Exception raised in Job[19]: TimeoutError()
Evaluating:  12%|█▎        | 25/200 [05:07<19:56,  6.84s/it]Exception raised in Job[30]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  13%|█▎        | 26/200 [05:08<15:05,  5.20s/it]Exception raised in Job[24]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  14%|█▎        | 27/200 [05:13<14:36,  5.07s/it]Exception raised in Job[25]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  14%|█▍        | 28/200 [05:15<11:57,  4.17s/it]Exception raised in Job[27]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  14%|█▍        | 29/200 [05:17<09:59,  3.51s/it]Exception raised in Job[23]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  15%|█▌        | 30/200 [05:17<07:23,  2.61s/it]Exception raised in Job[32]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  16%|█▌        | 31/200 [05:23<10:32,  3.74s/it]Exception raised in Job[22]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  16%|█▌        | 32/200 [05:26<09:23,  3.35s/it]Exception raised in Job[29]: TimeoutError()
Evaluating:  16%|█▋        | 33/200 [06:00<34:34, 12.42s/it]Exception raised in Job[33]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  17%|█▋        | 34/200 [06:35<53:04, 19.19s/it]Exception raised in Job[35]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  18%|█▊        | 35/200 [06:37<38:55, 14.15s/it]Exception raised in Job[34]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  18%|█▊        | 36/200 [06:39<28:29, 10.42s/it]Exception raised in Job[36]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Exception raised in Job[39]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  19%|█▉        | 38/200 [06:51<23:02,  8.53s/it]Exception raised in Job[42]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  20%|█▉        | 39/200 [07:14<32:15, 12.02s/it]Exception raised in Job[45]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  20%|██        | 40/200 [07:18<26:18,  9.87s/it]Exception raised in Job[37]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  20%|██        | 41/200 [07:19<20:15,  7.65s/it]Exception raised in Job[44]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  21%|██        | 42/200 [07:22<16:14,  6.17s/it]Exception raised in Job[38]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  22%|██▏       | 43/200 [07:32<19:05,  7.30s/it]Exception raised in Job[40]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  22%|██▏       | 44/200 [07:41<20:14,  7.78s/it]Exception raised in Job[46]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  22%|██▎       | 45/200 [07:49<20:20,  7.88s/it]Exception raised in Job[43]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  23%|██▎       | 46/200 [07:52<16:22,  6.38s/it]Exception raised in Job[41]: TimeoutError()
Evaluating:  24%|██▎       | 47/200 [08:08<23:36,  9.26s/it]Exception raised in Job[48]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  24%|██▍       | 48/200 [08:10<18:24,  7.27s/it]Exception raised in Job[47]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  24%|██▍       | 49/200 [08:16<17:14,  6.85s/it]Exception raised in Job[53]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  25%|██▌       | 50/200 [08:41<30:46, 12.31s/it]Exception raised in Job[50]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  26%|██▌       | 51/200 [08:48<26:23, 10.63s/it]Exception raised in Job[51]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  26%|██▌       | 52/200 [09:13<36:48, 14.92s/it]Exception raised in Job[49]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})

✓ Batch complete! 50 questions evaluated in 1893.8s
✓ Saved to CSV
============================================================

In [17]:
# ============================================================
# Cell 8: Fill HybridRAG RAGAS metrics (BATCH)
# ============================================================
# Columns: hybrid_faithfulness, hybrid_answer_relevancy,
#          hybrid_context_precision, hybrid_context_recall

df = pd.read_csv(CSV_PATH)

print('=' * 60)
print('  Computing RAGAS metrics for HybridRAG (BATCH)')
print('=' * 60)

# Find unfilled rows
unfilled_indices = []
for idx, row in df.iterrows():
    if is_empty(row.get('hybrid_faithfulness')):
        unfilled_indices.append(idx)
    else:
        print(f'[{idx+1}/{len(df)}] SKIP (already computed)')

if not unfilled_indices:
    print('\n✓ All rows already computed. Nothing to do.')
else:
    print(f'\n→ {len(unfilled_indices)} questions to evaluate (skipped {len(df) - len(unfilled_indices)})')
    
    questions = []
    answers = []
    contexts_list = []
    ground_truths = []
    
    for idx in unfilled_indices:
        row = df.iloc[idx]
        questions.append(row['question'])
        answers.append(str(row.get('hybridRAG_answer', '') or ''))
        ground_truths.append(str(row.get('ground_truth', '') or ''))
        contexts_list.append(extract_context_texts_from_hybrid(
            str(row.get('hybridRAG_sources', '{}') or '{}')
        ))
    
    print(f'→ Running batch RAGAS evaluation...')
    t0 = time.time()
    
    try:
        results = batch_ragas_evaluate(questions, answers, contexts_list, ground_truths)
        
        for i, idx in enumerate(unfilled_indices):
            df.at[idx, 'hybrid_faithfulness']      = results[i]['faithfulness']
            df.at[idx, 'hybrid_answer_relevancy']  = results[i]['answer_relevancy']
            df.at[idx, 'hybrid_context_precision'] = results[i]['context_precision']
            df.at[idx, 'hybrid_context_recall']    = results[i]['context_recall']
        
        elapsed = time.time() - t0
        df.to_csv(CSV_PATH, index=False)
        print(f'\n✓ Batch complete! {len(unfilled_indices)} questions evaluated in {elapsed:.1f}s')
        print(f'✓ Saved to CSV')
        
    except Exception as e:
        print(f'\n✗ Batch evaluation failed: {e}')
        print(f'⚠ Change API key in .env → re-run Cell 4 → re-run this cell')
        raise

print('=' * 60)

============================================================
  Computing RAGAS metrics for HybridRAG (BATCH)
============================================================

→ 50 questions to evaluate (skipped 0)
→ Running batch RAGAS evaluation...

Evaluating:   0%|          | 0/200 [00:00<?, ?it/s]Exception raised in Job[2]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   0%|          | 1/200 [01:48<5:58:39, 108.14s/it]Exception raised in Job[3]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   1%|          | 2/200 [01:58<2:47:18, 50.70s/it] Exception raised in Job[10]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   2%|▏         | 3/200 [02:00<1:33:36, 28.51s/it]Exception raised in Job[0]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   2%|▏         | 4/200 [02:01<57:04, 17.47s/it]  Exception raised in Job[9]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   2%|▎         | 5/200 [02:02<38:16, 11.78s/it]Exception raised in Job[1]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   3%|▎         | 6/200 [02:16<40:20, 12.48s/it]Exception raised in Job[6]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   4%|▎         | 7/200 [02:21<31:54,  9.92s/it]Exception raised in Job[8]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   4%|▍         | 8/200 [02:22<22:14,  6.95s/it]Exception raised in Job[7]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   4%|▍         | 9/200 [02:29<22:35,  7.10s/it]Exception raised in Job[4]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   5%|▌         | 10/200 [02:34<20:16,  6.40s/it]Exception raised in Job[13]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   6%|▌         | 11/200 [02:42<21:24,  6.79s/it]Exception raised in Job[15]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   6%|▌         | 12/200 [02:43<16:21,  5.22s/it]Exception raised in Job[5]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   6%|▋         | 13/200 [02:46<14:09,  4.54s/it]Exception raised in Job[12]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   7%|▋         | 14/200 [02:46<10:00,  3.23s/it]Exception raised in Job[14]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   8%|▊         | 15/200 [02:48<08:25,  2.73s/it]Exception raised in Job[11]: TimeoutError()
Evaluating:   8%|▊         | 16/200 [03:00<16:36,  5.41s/it]Exception raised in Job[26]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   8%|▊         | 17/200 [04:01<1:07:36, 22.16s/it]Exception raised in Job[19]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:   9%|▉         | 18/200 [04:14<59:19, 19.56s/it]  Exception raised in Job[20]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  10%|▉         | 19/200 [04:20<46:22, 15.37s/it]Exception raised in Job[28]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  10%|█         | 20/200 [04:20<32:25, 10.81s/it]Exception raised in Job[17]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  10%|█         | 21/200 [04:20<22:55,  7.69s/it]Exception raised in Job[16]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  11%|█         | 22/200 [04:24<19:02,  6.42s/it]Exception raised in Job[18]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  12%|█▏        | 23/200 [04:27<16:01,  5.43s/it]Exception raised in Job[27]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  12%|█▏        | 24/200 [04:37<19:44,  6.73s/it]Exception raised in Job[25]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  12%|█▎        | 25/200 [04:57<31:07, 10.67s/it]Exception raised in Job[24]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  13%|█▎        | 26/200 [04:57<22:12,  7.66s/it]Exception raised in Job[21]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  14%|█▎        | 27/200 [04:59<16:40,  5.79s/it]Exception raised in Job[31]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  14%|█▍        | 28/200 [05:08<19:45,  6.89s/it]Exception raised in Job[22]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  14%|█▍        | 29/200 [05:14<18:53,  6.63s/it]Exception raised in Job[23]: TimeoutError()
Evaluating:  15%|█▌        | 30/200 [05:22<19:29,  6.88s/it]Exception raised in Job[30]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  16%|█▌        | 31/200 [05:25<16:05,  5.71s/it]Exception raised in Job[29]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  16%|█▌        | 32/200 [05:40<23:58,  8.56s/it]Exception raised in Job[35]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  16%|█▋        | 33/200 [05:50<25:37,  9.21s/it]Exception raised in Job[32]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  17%|█▋        | 34/200 [06:18<40:38, 14.69s/it]Exception raised in Job[34]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  18%|█▊        | 35/200 [06:21<30:53, 11.23s/it]Exception raised in Job[37]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  18%|█▊        | 36/200 [06:28<26:46,  9.79s/it]Exception raised in Job[39]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  18%|█▊        | 37/200 [06:32<22:15,  8.19s/it]Exception raised in Job[36]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  19%|█▉        | 38/200 [06:38<20:07,  7.46s/it]Exception raised in Job[33]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  20%|█▉        | 39/200 [06:53<25:57,  9.68s/it]Exception raised in Job[42]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  20%|██        | 40/200 [06:59<23:33,  8.83s/it]Exception raised in Job[38]: TimeoutError()
Evaluating:  20%|██        | 41/200 [07:27<38:13, 14.42s/it]Exception raised in Job[43]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  21%|██        | 42/200 [07:31<29:49, 11.33s/it]Exception raised in Job[41]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  22%|██▏       | 43/200 [07:32<21:22,  8.17s/it]Exception raised in Job[40]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  22%|██▏       | 44/200 [07:34<16:29,  6.34s/it]Exception raised in Job[44]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  22%|██▎       | 45/200 [07:46<20:42,  8.02s/it]Exception raised in Job[51]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  23%|██▎       | 46/200 [07:50<17:25,  6.79s/it]Exception raised in Job[45]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  24%|██▎       | 47/200 [08:00<20:12,  7.93s/it]Exception raised in Job[46]: TimeoutError()
Evaluating:  24%|██▍       | 48/200 [08:25<32:26, 12.81s/it]Exception raised in Job[48]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Evaluating:  24%|██▍       | 49/200 [08:32<27:59, 11.13s/it]Exception raised in Job[47]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})
Exception raised in Job[54]: RateLimitError(Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}})

✓ Batch complete! 50 questions evaluated in 1835.1s
✓ Saved to CSV
============================================================

In [18]:
# ============================================================
# Cell 9: Fill combined metrics (averages)
# ============================================================
# Columns: combined_faithfulness, combined_answer_relevancy,
#          combined_context_precision, combined_context_recall

import numpy as np

df = pd.read_csv(CSV_PATH)

print('=' * 60)
print('  Computing Combined (Average) Metrics')
print('=' * 60)

metric_names = ['faithfulness', 'answer_relevancy', 'context_precision', 'context_recall']
rag_prefixes = ['vector', 'graph', 'hybrid']

skipped = 0
filled  = 0

for idx, row in df.iterrows():
    question = row['question']
    
    # --- SKIP if already computed ---
    if not is_empty(row.get('combined_faithfulness')):
        skipped += 1
        print(f'[{idx+1}/{len(df)}] SKIP (already computed)')
        continue
    
    print(f'[{idx+1}/{len(df)}] {question[:60]}...')
    
    for metric in metric_names:
        values = []
        for prefix in rag_prefixes:
            col = f'{prefix}_{metric}'
            val = row.get(col)
            if pd.notna(val):
                try:
                    values.append(float(val))
                except (ValueError, TypeError):
                    pass
        
        if values:
            df.at[idx, f'combined_{metric}'] = round(np.mean(values), 4)
        else:
            df.at[idx, f'combined_{metric}'] = None
    
    filled += 1

# Save
df.to_csv(CSV_PATH, index=False)
print(f'\n{"=" * 60}')
print(f'  ✓ Done! Skipped: {skipped}, Newly computed: {filled}')
print('=' * 60)

============================================================
  Computing Combined (Average) Metrics
============================================================
[1/50] What is the unique identification number (UIN) of the ICICI ...
[2/50] How does the policy document define 'Age' under Part-B?...
[3/50] What is the grace period allowed for a policyholder who has ...
[4/50] Where is the physical communication address of the ICICI Pru...
[5/50] After how many years from the date of policy issuance, risk ...
[6/50] What are the three authorized frequencies for premium paymen...
[7/50] How much does the company charge for issuing a duplicate cop...
[8/50] Who is defined as an 'Appointee' under Part-B of this policy...
[9/50] To which parties can benefits be legally payable according t...
[10/50] What is the maximum compensation limit that the Insurance Om...
[11/50] If a policyholder opts for a monthly premium payment mode, w...
[12/50] What is the Guaranteed Surrender Value (GSV) factor for a po...
[13/50] For a policy with a Premium Payment Term of 10 years, what i...
[14/50] What was the specific policy loan interest rate applicable i...
[15/50] What is the mathematical formula used to calculate the Paid-...
[16/50] What is the maximum percentage of the Surrender Value that a...
[17/50] If the 10-year Government Securities yield is sourced at 6.5...
[18/50] How is the Death Benefit 'B' calculated under Part-C?...
[19/50] Write out the full mathematical formula for calculating the ...
[20/50] Using the formula for policy years 8 to (Policy Term less 2)...
[21/50] How does converting a policy to 'paid-up' status affect futu...
[22/50] Compare the foreclosure rules for an active/fully paid polic...
[23/50] What additional documents are required to process a death cl...
[24/50] Explain the vesting rules when a policy is taken on a minor'...
[25/50] What is the general rule regarding a registered nomination w...
[26/50] If a policyholder commits suicide, how does the payout struc...
[27/50] How is the policy loan interest rate calculated, how frequen...
[28/50] Under Section 38, what are the four grounds on which an insu...
[29/50] How does the grace period differ across premium frequencies,...
[30/50] What are the specific conditions, time limits, and late paym...
[31/50] What is the exact waiting period specified in this document ...
[32/50] How much additional loyalty bonus is paid directly to the po...
[33/50] Under what circumstances can a policyholder request a partia...
[34/50] Which specific international stock market index is used to d...
[35/50] What is the maximum age limit up to which a policyholder can...
[36/50] How does the policy document define the 'Guaranteed Income B...
[37/50] What is the administrative fee and refund policy if a custom...
[38/50] How many free comprehensive medical examinations is the poli...
[39/50] Which specific third-party digital payment apps, such as Pay...
[40/50] What is the dynamic equity asset allocation ratio used by th...
[41/50] I just got my policy document yesterday but I changed my min...
[42/50] I missed my monthly premium payment date because I was trave...
[43/50] My policy has been in a reduced 'paid-up' state for the last...
[44/50] I am facing a financial emergency and need some quick cash. ...
[45/50] I paid my renewal premium by cheque, but it was returned due...
[46/50] My insurance agent offered to collect my renewal premium in ...
[47/50] I have lost my original policy bond. Is there a way to get a...
[48/50] I want to transfer my policy to my brother as a gift. What i...
[49/50] I want to name my 12-year-old daughter as my policy benefici...
[50/50] If I am unhappy with how the insurance company's grievance o...

============================================================
  ✓ Done! Skipped: 0, Newly computed: 50
============================================================

In [19]:
# ============================================================
# Cell 10: Final Summary & Verification
# ============================================================

df = pd.read_csv(CSV_PATH)

print('=' * 60)
print('  FINAL ANALYSIS SUMMARY')
print('=' * 60)
print(f'\nTotal questions: {len(df)}')
print(f'Columns: {len(df.columns)}')
print()

# Check completeness
for col in df.columns:
    non_null = df[col].notna().sum()
    pct = (non_null / len(df)) * 100
    status = '✓' if pct == 100 else '⚠' if pct > 0 else '✗'
    print(f'  {status} {col}: {non_null}/{len(df)} filled ({pct:.0f}%)')

print()
print('─' * 60)
print('METRIC AVERAGES ACROSS ALL QUESTIONS')
print('─' * 60)

metric_cols = [
    'vector_faithfulness', 'vector_answer_relevancy', 'vector_context_precision', 'vector_context_recall',
    'graph_faithfulness', 'graph_answer_relevancy', 'graph_context_precision', 'graph_context_recall',
    'hybrid_faithfulness', 'hybrid_answer_relevancy', 'hybrid_context_precision', 'hybrid_context_recall',
    'combined_faithfulness', 'combined_answer_relevancy', 'combined_context_precision', 'combined_context_recall',
]

for col in metric_cols:
    if col in df.columns:
        mean_val = pd.to_numeric(df[col], errors='coerce').mean()
        print(f'  {col}: {mean_val:.4f}')

print()
print('✓ All done! finalAnalysis.csv is fully populated.')
df.head(20)

============================================================
  FINAL ANALYSIS SUMMARY
============================================================

Total questions: 50
Columns: 25

  ✓ question: 50/50 filled (100%)
  ✓ question_type: 50/50 filled (100%)
  ✓ ground_truth: 50/50 filled (100%)
  ✓ vectorRAG_answer: 50/50 filled (100%)
  ✓ graphRAG_answer: 50/50 filled (100%)
  ✓ hybridRAG_answer: 50/50 filled (100%)
  ✓ vectorRAG_sources: 50/50 filled (100%)
  ✓ graphRAG_triplets: 50/50 filled (100%)
  ✓ hybridRAG_sources: 50/50 filled (100%)
  ⚠ vector_faithfulness: 43/50 filled (86%)
  ✗ graph_faithfulness: 0/50 filled (0%)
  ✗ hybrid_faithfulness: 0/50 filled (0%)
  ⚠ vector_answer_relevancy: 28/50 filled (56%)
  ✗ graph_answer_relevancy: 0/50 filled (0%)
  ✗ hybrid_answer_relevancy: 0/50 filled (0%)
  ⚠ vector_context_precision: 23/50 filled (46%)
  ✗ graph_context_precision: 0/50 filled (0%)
  ✗ hybrid_context_precision: 0/50 filled (0%)
  ⚠ vector_context_recall: 45/50 filled (90%)
  ✗ graph_context_recall: 0/50 filled (0%)
  ✗ hybrid_context_recall: 0/50 filled (0%)
  ⚠ combined_faithfulness: 43/50 filled (86%)
  ⚠ combined_answer_relevancy: 28/50 filled (56%)
  ⚠ combined_context_precision: 23/50 filled (46%)
  ⚠ combined_context_recall: 45/50 filled (90%)

────────────────────────────────────────────────────────────
METRIC AVERAGES ACROSS ALL QUESTIONS
────────────────────────────────────────────────────────────
  vector_faithfulness: 0.6547
  vector_answer_relevancy: 0.9013
  vector_context_precision: 0.6464
  vector_context_recall: 0.9444
  graph_faithfulness: nan
  graph_answer_relevancy: nan
  graph_context_precision: nan
  graph_context_recall: nan
  hybrid_faithfulness: nan
  hybrid_answer_relevancy: nan
  hybrid_context_precision: nan
  hybrid_context_recall: nan
  combined_faithfulness: 0.6547
  combined_answer_relevancy: 0.9014
  combined_context_precision: 0.6464
  combined_context_recall: 0.9444

✓ All done! finalAnalysis.csv is fully populated.

,question,question_type,ground_truth,vectorRAG_answer,graphRAG_answer,hybridRAG_answer,vectorRAG_sources,graphRAG_triplets,hybridRAG_sources,vector_faithfulness,...,vector_context_precision,graph_context_precision,hybrid_context_precision,vector_context_recall,graph_context_recall,hybrid_context_recall,combined_faithfulness,combined_answer_relevancy,combined_context_precision,combined_context_recall
0,What is the unique identification number (UIN)...,Basic Retrieval,The UIN of the policy is 105N153V04.,The unique identification number (UIN) of the ...,⚠️ The requested information was not found in ...,The unique identification number (UIN) of the ...,"[{""text"": ""later of Policy Issue Date or ...","[{""subject"": ""ICICI Prudential Life Insurance ...","{""vector_sources"": [{""text"": ""later of Polic...",1.000000,...,0.500000,NaN,NaN,1.0,NaN,NaN,1.0000,1.0000,0.5000,1.0
1,How does the policy document define 'Age' unde...,Basic Retrieval,'Age' means the age of the Life Assured in com...,"According to Part-B of the policy document, 'A...",⚠️ The requested information was not found in ...,"According to the policy document, 'Age' under ...","[{""text"": ""Policy Document - Terms and Conditi...","[{""subject"": ""Policy document"", ""subject_type""...","{""vector_sources"": [{""text"": ""Policy Document ...",0.666667,...,1.000000,NaN,NaN,1.0,NaN,NaN,0.6667,0.8952,1.0000,1.0
2,What is the grace period allowed for a policyh...,Basic Retrieval,A grace period of 15 days from the premium due...,The grace period allowed for a policyholder wh...,To determine the grace period allowed for a po...,The grace period allowed for a policyholder wh...,"[{""text"": ""If you are unable to pay Instalment...","[{""subject"": ""Grace Period"", ""subject_type"": ""...","{""vector_sources"": [{""text"": ""If you are unabl...",0.250000,...,1.000000,NaN,NaN,1.0,NaN,NaN,0.2500,1.0000,1.0000,1.0
3,Where is the physical communication address of...,Basic Retrieval,"Customer Service Desk, ICICI Prudential Life I...",The physical communication address of the ICIC...,To find the physical communication address of ...,The physical communication address of the ICIC...,"[{""text"": ""Insurance Ombudsman. We request ...","[{""subject"": ""ICICI Prudential Life Insurance ...","{""vector_sources"": [{""text"": ""Insurance Ombud...",0.333333,...,0.500000,NaN,NaN,1.0,NaN,NaN,0.3333,1.0000,0.5000,1.0
4,After how many years from the date of policy i...,Basic Retrieval,No policy of Life Insurance shall be called in...,A life insurance policy cannot be questioned o...,"After analyzing the knowledge graph triplets, ...",A life insurance policy cannot be questioned o...,"[{""text"": ""from a) the date of issuance of pol...","[{""subject"": ""Policy of Life Insurance"", ""subj...","{""vector_sources"": [{""text"": ""from a) the date...",0.555556,...,NaN,NaN,NaN,1.0,NaN,NaN,0.5556,0.8846,NaN,1.0
5,What are the three authorized frequencies for ...,Basic Retrieval,"The premiums can be paid in yearly, half-yearl...",The three authorized frequencies for premium p...,The three authorized frequencies for premium p...,The three authorized frequencies for premium p...,"[{""text"": ""base premium and the extra mor...","[{""subject"": ""Premiums"", ""subject_type"": ""PAYM...","{""vector_sources"": [{""text"": ""base premium a...",1.000000,...,1.000000,NaN,NaN,1.0,NaN,NaN,1.0000,0.8493,1.0000,1.0
6,How much does the company charge for issuing a...,Basic Retrieval,The current charge for the issuance of a dupli...,The company charges ₹ 200 for issuing a duplic...,⚠️ The requested information was not found in ...,The company charges ₹ 200 for issuing a duplic...,"[{""text"": ""charges for issuance of duplicate p...","[{""subject"": ""duplicate policy document"", ""sub...","{""vector_sources"": [{""text"": ""charges for issu...",0.333333,...,1.000000,NaN,NaN,1.0,NaN,NaN,0.3333,1.0000,1.0000,1.0
7,Who is defined as an 'Appointee' under Part-B ...,Basic Retrieval,An Appointee is the person appointed by the po...,"According to Part-B of the policy, an 'Appoint...",⚠️ The requested information was not found in ...,An 'Appointee' is defined as the person appoin...,"[{""text"": ""or Company means ICICI Prudenti...","[{""subject"": ""Appointee"", ""subject_type"": ""POL...","{""vector_sources"": [{""text"": ""or Company mea...",0.333333,...,0.500000,NaN,NaN,1.0,NaN,NaN,0.3333,0.9308,0.5000,1.0
8,To which parties can benefits be legally payab...,Basic Retrieval,"Benefits are payable to the Policyholder, to t...","According to the provided document sections, b...","According to the knowledge graph, benefits can...","Benefits can be payable to the policyholder, a...","[{""text"": ""vi.On payment of this paid-up death...","[{""subject"": ""benefits payable under the Polic...","{""vector_sources"": [{""text"": ""vi.On payment of...",0.833333,...,NaN,NaN,NaN,1.0,NaN,NaN,0.8333,0.7298,NaN,1.0
9,What is the maximum compensation limit that th...,Basic Retrieval,The Ombudsman shall not award compensation exc...,The maximum compensation limit that the Insura...,⚠️ The requested information was not found in ...,The maximum compensation limit that the Insura...,"[{""text"": ""in case the delay is condoned, the ...","[{""subject"": ""Insurance Ombudsman (Amendment) ...","{""vector_sources"": [{""text"": ""in case the dela...",0.666667,...,1.000000,NaN,NaN,1.0,NaN,NaN,0.6667,0.9035,1.0000,1.0
10,If a policyholder opts for a monthly premium p...,Numerical Reasoning,A premium loading of 4.5% is applied for the m...,"According to the provided context, if a policy...",To find the loading percentage applied to the ...,If a policyholder opts for a monthly premium p...,"[{""text"": ""base premium and the extra mor...","[{""subject"": ""Monthly and half-yearly premium ...","{""vector_sources"": [{""text"": ""base premium a...",0.400000,...,1.000000,NaN,NaN,1.0,NaN,NaN,0.4000,0.9435,1.0000,1.0
11,What is the Guaranteed Surrender Value (GSV) f...,Numerical Reasoning,The GSV factor for policy year 3 is 35%.,The Guaranteed Surrender Value (GSV) factor fo...,The Guaranteed Surrender Value (GSV) factor fo...,The Guaranteed Surrender Value (GSV) factor fo...,"[{""text"": ""Policy shall terminate on payme...","[{""subject"": ""GSV factor"", ""subject_type"": ""FI...","{""vector_sources"": [{""text"": ""Policy shall t...",0.200000,...,NaN,NaN,NaN,1.0,NaN,NaN,0.2000,0.9748,NaN,1.0
12,For a policy with a Premium Payment Term of 10...,Numerical Reasoning,The GA rate is 15% of the annualized premium f...,For a policy with a Premium Payment Term of 10...,To determine the Guaranteed Additions (GAs) ra...,The Guaranteed Additions (GAs) rate for policy...,"[{""text"": ""frequency, 1/12th times GA will be ...","[{""subject"": ""Guaranteed Additions (GAs)"", ""su...","{""vector_sources"": [{""text"": ""frequency, 1/12t...",1.000000,...,NaN,NaN,NaN,1.0,NaN,NaN,1.0000,0.8809,NaN,1.0
13,What was the specific policy loan interest rat...,Numerical Reasoning,The loan interest rate in September 2025 was 8...,The specific policy loan interest rate applica...,The specific policy loan interest rate applica...,The specific policy loan interest rate applica...,"[{""text"": ""Policy. On Foreclosure, the Pol...","[{""subject"": ""Loan Interest Rate"", ""subject_ty...","{""vector_sources"": [{""text"": ""Policy. On For...",0.500000,...,1.000000,NaN,NaN,1.0,NaN,NaN,0.5000,0.8805,1.0000,1.0
14,What is the mathematical formula used to calcu...,Numerical Reasoning,Paid-up GMB = GMB X (number of months for whic...,The mathematical formula used to calculate the...,⚠️ The requested information was not found in ...,The mathematical formula used to calculate the...,"[{""text"": ""total premiums paid } ii.Paid-up Gu...","[{""subject"": ""Guaranteed Maturity Benefit (GMB...","{""vector_sources"": [{""text"": ""total premiums p...",0.500000,...,NaN,NaN,NaN,1.0,NaN,NaN,0.5000,1.0000,NaN,1.0
15,What is the maximum percentage of the Surrende...,Numerical Reasoning,A loan of up to 80% of the Surrender Value can...,The maximum percentage of the Surrender Value ...,⚠️ The requested information was not found in ...,The maximum percentage of the Surrender Value ...,"[{""text"": ""Policy. On Foreclosure, the Pol...","[{""subject"": ""Surrender value"", ""subject_type""...","{""vector_sources"": [{""text"": ""Policy. On For...",0.200000,...,0.333333,NaN,NaN,1.0,NaN,NaN,0.2000,1.0000,0.3333,1.0
16,If the 10-year Government Securities yield is ...,Numerical Reasoning,The interest rate will be 8.00% (since the pol...,The applicable policy loan interest rate can b...,To determine the applicable policy loan intere...,If the 10-year Government Securities yield is ...,"[{""text"": ""Policy. On Foreclosure, the Pol...","[{""subject"": ""10-year Government Securities Yi...","{""vector_sources"": [{""text"": ""Policy. On For...",0.500000,...,1.000000,NaN,NaN,1.0,NaN,NaN,0.5000,0.9262,1.0000,1.0
17,How is the Death Benefit 'B' calculated under ...,Numerical Reasoning,Death Benefit B is calculated as 105% of the t...,"The Death Benefit 'B' is calculated as ""105% o...","To calculate the Death Benefit 'B', we refer t...",The Death Benefit 'B' is calculated as 105% of...,"[{""text"": ""total premiums paid } ii.Paid-up Gu...","[{""subject"": ""Death Benefit Formula"", ""subject...","{""vector_sources"": [{""text"": ""total premiums p...",0.800000,...,0.200000,NaN,NaN,1.0,NaN,NaN,0.8000,0.8645,0.2000,1.0
18,Write out the full mathematical formula for ca...,Numerical Reasoning,GSV = (GSV Factor X Total premiums paid) + 30%...,The full mathematical formula for calculating ...,⚠️ The requested information was not found in ...,The full mathematical formula for calculating ...,"[{""text"": ""Guaranteed Additions). GSV factors...","[{""subject"": ""GSV Formula"", ""subject_type"": ""F...","{""vector_sources"": [{""text"": ""Guaranteed Addit...",1.000000,...,0.500000,NaN,NaN,1.0,NaN,NaN,1.0000,0.9645,0.5000,1.0
19,Using the formula for policy years 8 to (Polic...,Numerical Reasoning,Using the formula: 50% + 40% x (Policy Year - ...,To calculate the GSV factor for policy year 10...,To calculate the GSV factor for policy year 10...,To calculate the GSV factor for policy year 10...,"[{""text"": ""Policy shall terminate on payme...","[{""subject"": ""Policy Years 8 to (Policy Term -...","{""vector_sources"": [{""text"": ""Policy shall t...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9023,NaN,NaN